/*
 * Copyright (C) 2026 Keliver contributors.
 * Licensed under the Apache License, Version 2.0.
 */
package dev.keliver.sample.host

import androidx.compose.foundation.layout.Box as ComposeBox
import androidx.compose.foundation.layout.Column as ComposeColumn
import androidx.compose.foundation.layout.Row as ComposeRow
import androidx.compose.foundation.layout.Spacer as ComposeSpacer
import androidx.compose.foundation.layout.height
import androidx.compose.material.Button as ComposeButton
import androidx.compose.material.Card as ComposeCard
import androidx.compose.material.Checkbox as ComposeCheckbox
import androidx.compose.material.Text as ComposeText
import androidx.compose.material.TextField as ComposeTextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier as ComposeModifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import dev.keliver.sample.schema.widget.Box
import dev.keliver.sample.schema.widget.Button
import dev.keliver.sample.schema.widget.Card
import dev.keliver.sample.schema.widget.Checkbox
import dev.keliver.sample.schema.widget.Column
import dev.keliver.sample.schema.widget.Row
import dev.keliver.sample.schema.widget.SampleSchemaWidgetFactory
import dev.keliver.sample.schema.widget.Spacer
import dev.keliver.sample.schema.widget.Text
import dev.keliver.sample.schema.widget.TextField
import dev.keliver.widget.Widget
import dev.keliver.widget.compose.ComposeWidgetChildren

/**
 * Host-side renderer signature. Every widget impl provides a `value` of
 * this type — a Composable that paints itself into the host's Compose
 * tree, given an incoming Modifier from the parent.
 *
 * The `WidgetSystem` Keliver hands to `TreehouseContent` is parameterized
 * over this signature; that's how the host plugs in its rendering layer
 * without Keliver having to know about Compose.
 */
public typealias CmpRender = @Composable (ComposeModifier) -> Unit

/**
 * Binds each codegen'd widget interface in the schema to a concrete
 * Compose impl. `SampleSchemaWidgetFactory` is generated by
 * `:shared-widget` from the `@Schema` declaration — adding a new widget
 * there means adding a new `override fun Foo()` here plus a `CmpFoo` class.
 */
public object CmpWidgetFactory : SampleSchemaWidgetFactory<CmpRender> {
  override fun Box(): Box<CmpRender> = CmpBox()
  override fun Text(): Text<CmpRender> = CmpText()
  override fun Column(): Column<CmpRender> = CmpColumn()
  override fun Row(): Row<CmpRender> = CmpRow()
  override fun Button(): Button<CmpRender> = CmpButton()
  override fun Spacer(): Spacer<CmpRender> = CmpSpacer()
  override fun Card(): Card<CmpRender> = CmpCard()
  override fun TextField(): TextField<CmpRender> = CmpTextField()
  override fun Checkbox(): Checkbox<CmpRender> = CmpCheckbox()
}

/**
 * `Box` impl. A single `Children(1)` slot in the schema becomes a
 * `Widget.Children<CmpRender>` here — Keliver injects the host's
 * `ComposeWidgetChildren` so the guest's child widgets render inside the
 * Compose Box layout.
 */
private class CmpBox : Box<CmpRender> {
  override val children: Widget.Children<CmpRender> = ComposeWidgetChildren()
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeBox(modifier = incoming) {
      (children as ComposeWidgetChildren).Render()
    }
  }
}

/** `Column` impl — renders its children slot in a Compose Column. */
private class CmpColumn : Column<CmpRender> {
  override val children: Widget.Children<CmpRender> = ComposeWidgetChildren()
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeColumn(modifier = incoming) {
      (children as ComposeWidgetChildren).Render()
    }
  }
}

/** `Row` impl — renders its children slot in a Compose Row. */
private class CmpRow : Row<CmpRender> {
  override val children: Widget.Children<CmpRender> = ComposeWidgetChildren()
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeRow(modifier = incoming) {
      (children as ComposeWidgetChildren).Render()
    }
  }
}

/**
 * `Text` impl. The `@Property(1) text` from the schema becomes the
 * `text(value)` setter below. `mutableStateOf` makes recomposition
 * automatic when the guest updates the value.
 */
private class CmpText : Text<CmpRender> {
  private var textValue by mutableStateOf("")
  private var fontSizeValue by mutableStateOf(14)
  private var boldValue by mutableStateOf(false)
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeText(
      text = textValue,
      fontSize = fontSizeValue.sp,
      fontWeight = if (boldValue) FontWeight.Bold else FontWeight.Normal,
      modifier = incoming,
    )
  }

  override fun text(text: String) {
    textValue = text
  }

  override fun fontSize(fontSize: Int) {
    fontSizeValue = fontSize
  }

  override fun bold(bold: Boolean) {
    boldValue = bold
  }
}

/**
 * `Button` impl. `text` is a normal property; `onClick` is an event —
 * the host invokes the stored lambda on tap, and Keliver routes that call
 * back across the Zipline bridge so the guest's `onClick` actually runs.
 */
private class CmpButton : Button<CmpRender> {
  private var textValue by mutableStateOf("")
  private var onClickValue by mutableStateOf<(() -> Unit)?>(null)
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeButton(onClick = { onClickValue?.invoke() }, modifier = incoming) {
      ComposeText(text = textValue)
    }
  }

  override fun text(text: String) {
    textValue = text
  }

  override fun onClick(onClick: (() -> Unit)?) {
    onClickValue = onClick
  }
}

/** `Spacer` impl — a fixed-height gap. `height` is in dp. */
private class CmpSpacer : Spacer<CmpRender> {
  private var heightValue by mutableStateOf(0)
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeSpacer(modifier = incoming.then(ComposeModifier.height(heightValue.dp)))
  }

  override fun height(height: Int) {
    heightValue = height
  }
}

/** `Card` impl — children render inside a Material Card. */
private class CmpCard : Card<CmpRender> {
  override val children: Widget.Children<CmpRender> = ComposeWidgetChildren()
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeCard(modifier = incoming) {
      (children as ComposeWidgetChildren).Render()
    }
  }
}

/**
 * `TextField` impl. `value`/`placeholder` are properties; `onValueChange`
 * is a parameterized event — the host fires it with the new text on each
 * keystroke and Keliver routes the value back to the guest.
 */
private class CmpTextField : TextField<CmpRender> {
  private var valueState by mutableStateOf("")
  private var placeholderState by mutableStateOf("")
  private var onValueChangeValue by mutableStateOf<((String) -> Unit)?>(null)
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeTextField(
      value = valueState,
      onValueChange = { onValueChangeValue?.invoke(it) },
      placeholder = { ComposeText(text = placeholderState) },
      singleLine = true,
      modifier = incoming,
    )
  }

  override fun value(value: String) {
    valueState = value
  }

  override fun placeholder(placeholder: String) {
    placeholderState = placeholder
  }

  override fun onValueChange(onValueChange: ((String) -> Unit)?) {
    onValueChangeValue = onValueChange
  }
}

/** `Checkbox` impl — `onCheckedChange` fires with the new state on toggle. */
private class CmpCheckbox : Checkbox<CmpRender> {
  private var checkedState by mutableStateOf(false)
  private var onCheckedChangeValue by mutableStateOf<((Boolean) -> Unit)?>(null)
  override var modifier: dev.keliver.Modifier = dev.keliver.Modifier

  override val value: CmpRender = { incoming ->
    ComposeCheckbox(
      checked = checkedState,
      onCheckedChange = { onCheckedChangeValue?.invoke(it) },
      modifier = incoming,
    )
  }

  override fun checked(checked: Boolean) {
    checkedState = checked
  }

  override fun onCheckedChange(onCheckedChange: ((Boolean) -> Unit)?) {
    onCheckedChangeValue = onCheckedChange
  }
}
