/*
 * Copyright (C) 2026 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.keliver.http.api

/**
 * Marks a Kotlin interface as a Keliver HTTP API. The
 * `keliver-http-codegen` KSP processor (queued — see
 * `docs/HTTP_API_CODEGEN_DESIGN.md`) walks every method on this
 * interface, reads the HTTP-method + parameter annotations, and
 * generates an implementation class backed by a
 * [dev.keliver.http.KeliverHttp] instance.
 *
 * ```
 * @KeliverApi
 * interface QuotesApi {
 *     @GET("/quotes")
 *     suspend fun list(
 *         @Query("filter") filter: String?,
 *         @Query("limit") limit: Int,
 *     ): List<Quote>
 *
 *     @POST("/quotes")
 *     suspend fun create(@Body body: NewQuote): Quote
 * }
 *
 * // Generated by the KSP processor (planned):
 * //   class QuotesApiImpl(private val http: KeliverHttp) : QuotesApi
 *
 * // Adopter usage:
 * //   val api = QuotesApiImpl(KeliverHttp(httpProviderBridge))
 * //   val quotes = api.list(filter = null, limit = 20)
 * ```
 *
 * All annotated methods must be `suspend` and have a return type that
 * kotlinx-serialization can resolve a `KSerializer` for. The processor
 * fails the build with a diagnostic if these constraints are violated
 * (rather than the silent-no-op shape KNOWN_BUGS U4 used to surface).
 *
 * Status: annotations are stable. KSP processor is queued for the
 * next development cycle. Adopters writing `@KeliverApi` interfaces
 * today can either implement them manually against [KeliverHttp]
 * until the processor lands, or wait for the auto-generated impl.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
public annotation class KeliverApi
