/*
 * Copyright (C) 2026 Konduit contributors.
 * Licensed under the Apache License, Version 2.0.
 */
package dev.keliver.http.api

/**
 * Marks a Kotlin interface as a Konduit HTTP API. The
 * `konduit-http-codegen` KSP processor (queued — see
 * `docs/HTTP_API_CODEGEN_DESIGN.md`) walks every method on this
 * interface, reads the HTTP-method + parameter annotations, and
 * generates an implementation class backed by a
 * [dev.keliver.http.KonduitHttp] instance.
 *
 * ```
 * @KonduitApi
 * interface QuotesApi {
 *     @GET("/quotes")
 *     suspend fun list(
 *         @Query("filter") filter: String?,
 *         @Query("limit") limit: Int,
 *     ): List<Quote>
 *
 *     @POST("/quotes")
 *     suspend fun create(@Body body: NewQuote): Quote
 * }
 *
 * // Generated by the KSP processor (planned):
 * //   class QuotesApiImpl(private val http: KonduitHttp) : QuotesApi
 *
 * // Adopter usage:
 * //   val api = QuotesApiImpl(KonduitHttp(httpProviderBridge))
 * //   val quotes = api.list(filter = null, limit = 20)
 * ```
 *
 * All annotated methods must be `suspend` and have a return type that
 * kotlinx-serialization can resolve a `KSerializer` for. The processor
 * fails the build with a diagnostic if these constraints are violated
 * (rather than the silent-no-op shape KNOWN_BUGS U4 used to surface).
 *
 * Status: annotations are stable. KSP processor is queued for the
 * next development cycle. Adopters writing `@KonduitApi` interfaces
 * today can either implement them manually against [KonduitHttp]
 * until the processor lands, or wait for the auto-generated impl.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
public annotation class KonduitApi
