// GENERATED by :portal-schema-codegen — do not edit. Run ./gradlew :portal-schema-codegen:generatePortalCode
package dev.keliver.portal

private val composableImport: Map<String, String> = mapOf(
  "AlertDialog" to "dev.keliver.material.compose.AlertDialog",
  "AnimatedBorder" to "dev.keliver.material.compose.AnimatedBorder",
  "AnimatedVisibility" to "dev.keliver.material.compose.AnimatedVisibility",
  "AsyncImage" to "dev.keliver.material.compose.AsyncImage",
  "Badge" to "dev.keliver.material.compose.Badge",
  "BottomAppBar" to "dev.keliver.material.compose.BottomAppBar",
  "BottomSheet" to "dev.keliver.material.compose.BottomSheet",
  "Box" to "dev.keliver.layout.compose.Box",
  "Button" to "dev.keliver.material.compose.Button",
  "Card" to "dev.keliver.material.compose.Card",
  "Checkbox" to "dev.keliver.material.compose.Checkbox",
  "Chip" to "dev.keliver.material.compose.Chip",
  "CircularProgressIndicator" to "dev.keliver.material.compose.CircularProgressIndicator",
  "Clickable" to "dev.keliver.material.compose.Clickable",
  "Column" to "dev.keliver.layout.compose.Column",
  "Dialog" to "dev.keliver.material.compose.Dialog",
  "Divider" to "dev.keliver.material.compose.Divider",
  "ElevatedButton" to "dev.keliver.material.compose.ElevatedButton",
  "ElevatedCard" to "dev.keliver.material.compose.ElevatedCard",
  "ExtendedFloatingActionButton" to "dev.keliver.material.compose.ExtendedFloatingActionButton",
  "FilledTonalButton" to "dev.keliver.material.compose.FilledTonalButton",
  "FilterChip" to "dev.keliver.material.compose.FilterChip",
  "FloatingActionButton" to "dev.keliver.material.compose.FloatingActionButton",
  "FlowColumn" to "dev.keliver.material.compose.FlowColumn",
  "FlowRow" to "dev.keliver.material.compose.FlowRow",
  "HorizontalPager" to "dev.keliver.material.compose.HorizontalPager",
  "IconButton" to "dev.keliver.material.compose.IconButton",
  "Image" to "dev.keliver.material.compose.Image",
  "InputChip" to "dev.keliver.material.compose.InputChip",
  "LazyHorizontalGrid" to "dev.keliver.material.compose.LazyHorizontalGrid",
  "LazyVerticalGrid" to "dev.keliver.material.compose.LazyVerticalGrid",
  "LinearProgressIndicator" to "dev.keliver.material.compose.LinearProgressIndicator",
  "NavigationBar" to "dev.keliver.material.compose.NavigationBar",
  "NavigationRail" to "dev.keliver.material.compose.NavigationRail",
  "OutlinedButton" to "dev.keliver.material.compose.OutlinedButton",
  "OutlinedCard" to "dev.keliver.material.compose.OutlinedCard",
  "OutlinedTextField" to "dev.keliver.material.compose.OutlinedTextField",
  "RadioButton" to "dev.keliver.material.compose.RadioButton",
  "Row" to "dev.keliver.layout.compose.Row",
  "ScrollableColumn" to "dev.keliver.material.compose.ScrollableColumn",
  "Shimmer" to "dev.keliver.material.compose.Shimmer",
  "Slider" to "dev.keliver.material.compose.Slider",
  "Snackbar" to "dev.keliver.material.compose.Snackbar",
  "Spacer" to "dev.keliver.layout.compose.Spacer",
  "StyledBox" to "dev.keliver.material.compose.StyledBox",
  "StyledText" to "dev.keliver.material.compose.StyledText",
  "SuggestionChip" to "dev.keliver.material.compose.SuggestionChip",
  "Surface" to "dev.keliver.material.compose.Surface",
  "Switch" to "dev.keliver.material.compose.Switch",
  "Tab" to "dev.keliver.material.compose.Tab",
  "TabRow" to "dev.keliver.material.compose.TabRow",
  "Text" to "dev.keliver.material.compose.Text",
  "TextButton" to "dev.keliver.material.compose.TextButton",
  "TextField" to "dev.keliver.material.compose.TextField",
  "TextInput" to "dev.keliver.material.compose.TextInput",
  "Theme" to "dev.keliver.material.compose.Theme",
  "Tooltip" to "dev.keliver.material.compose.Tooltip",
  "TopAppBar" to "dev.keliver.material.compose.TopAppBar",
  "VerticalDivider" to "dev.keliver.material.compose.VerticalDivider",
  "VerticalPager" to "dev.keliver.material.compose.VerticalPager",
)

private val supportImports: Map<String, List<String>> = mapOf(
  "Box" to listOf("dev.keliver.layout.api.Constraint", "dev.keliver.layout.api.CrossAxisAlignment"),
  "Column" to listOf("dev.keliver.layout.api.Constraint", "dev.keliver.layout.api.CrossAxisAlignment", "dev.keliver.layout.api.MainAxisAlignment", "dev.keliver.layout.api.Overflow"),
  "Row" to listOf("dev.keliver.layout.api.Constraint", "dev.keliver.layout.api.CrossAxisAlignment", "dev.keliver.layout.api.MainAxisAlignment", "dev.keliver.layout.api.Overflow"),
  "Spacer" to listOf("dev.keliver.ui.Dp"),
)

private fun collectTypes(node: WidgetNode, out: MutableSet<String>) {
  out += node.type
  node.children.forEach { collectTypes(it, out) }
}

private fun fmtString(v: Any?): String = "\"" + v.toString().replace("\\", "\\\\").replace("\"", "\\\"") + "\""
private fun fmtInt(v: Any?): String = ((v as? Int) ?: 0).toString()
private fun fmtBool(v: Any?): String = ((v as? Boolean) ?: false).toString()
private fun fmtDouble(v: Any?): String = ((v as? Double) ?: (v as? Int)?.toDouble() ?: 0.0).toString()
private fun fmtFloat(v: Any?): String = "${fmtDouble(v)}f"
private fun fmtDp(v: Any?): String = "Dp(${fmtDouble(v)})"
private fun fmtIntList(v: Any?): String = "listOf(" + ((v as? List<*>)?.joinToString(", ") ?: "") + ")"
private fun fmtFloatList(v: Any?): String = "listOf(" + ((v as? List<*>)?.joinToString(", ") { "${it}f" } ?: "") + ")"
private fun fmtConstraint(v: Any?): String = if (((v as? Int) ?: 0) == 1) "Constraint.Fill" else "Constraint.Wrap"
private fun fmtCrossAxis(v: Any?): String = when ((v as? Int) ?: 0) {
  1 -> "CrossAxisAlignment.Center"
  2 -> "CrossAxisAlignment.End"
  3 -> "CrossAxisAlignment.Stretch"
  else -> "CrossAxisAlignment.Start"
}
private fun fmtOverflow(v: Any?): String = if (((v as? Int) ?: 0) == 1) "Overflow.Scroll" else "Overflow.Clip"
private fun fmtMainAxis(v: Any?): String = when ((v as? Int) ?: 0) {
  1 -> "MainAxisAlignment.Center"
  2 -> "MainAxisAlignment.End"
  3 -> "MainAxisAlignment.SpaceBetween"
  4 -> "MainAxisAlignment.SpaceAround"
  5 -> "MainAxisAlignment.SpaceEvenly"
  else -> "MainAxisAlignment.Start"
}

fun exportKotlin(tree: WidgetNode, functionName: String = "ExportedScreen"): String {
  val used = mutableSetOf<String>()
  collectTypes(tree, used)
  val sb = StringBuilder()
  sb.append("import androidx.compose.runtime.Composable\n")
  val imports = (used.mapNotNull { composableImport[it] } + used.flatMap { supportImports[it] ?: emptyList() }).distinct().sorted()
  imports.forEach { sb.append("import $it\n") }
  sb.append("\n@Composable\nfun $functionName() {\n")
  emitNode(sb, tree, "  ")
  sb.append("}\n")
  return sb.toString()
}

private fun emitNode(sb: StringBuilder, node: WidgetNode, indent: String) {
  when (node.type) {
    "AlertDialog" -> {
      sb.append("${indent}AlertDialog(\n")
      sb.append("${indent}  title = ${fmtString(node.props["title"] ?: "")},\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("confirmText" in node.props) sb.append("${indent}  confirmText = ${fmtString(node.props["confirmText"] ?: "")},\n")
      if ("dismissText" in node.props) sb.append("${indent}  dismissText = ${fmtString(node.props["dismissText"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "AnimatedBorder" -> {
      sb.append("${indent}AnimatedBorder(\n")
      if ("cornerRadiusDp" in node.props) sb.append("${indent}  cornerRadiusDp = ${fmtInt(node.props["cornerRadiusDp"])},\n")
      if ("strokeWidthDp" in node.props) sb.append("${indent}  strokeWidthDp = ${fmtInt(node.props["strokeWidthDp"])},\n")
      if ("baseColorArgb" in node.props) sb.append("${indent}  baseColorArgb = ${fmtInt(node.props["baseColorArgb"])},\n")
      if ("cometColorArgb" in node.props) sb.append("${indent}  cometColorArgb = ${fmtInt(node.props["cometColorArgb"])},\n")
      if ("durationMs" in node.props) sb.append("${indent}  durationMs = ${fmtInt(node.props["durationMs"])},\n")
      if ("segmentLenDp" in node.props) sb.append("${indent}  segmentLenDp = ${fmtInt(node.props["segmentLenDp"])},\n")
      if ("effect" in node.props) sb.append("${indent}  effect = ${fmtInt(node.props["effect"])},\n")
      if ("colorsArgb" in node.props) sb.append("${indent}  colorsArgb = ${fmtIntList(node.props["colorsArgb"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "AnimatedVisibility" -> {
      sb.append("${indent}AnimatedVisibility(\n")
      if ("visible" in node.props) sb.append("${indent}  visible = ${fmtBool(node.props["visible"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "AsyncImage" -> {
      sb.append("${indent}AsyncImage(\n")
      sb.append("${indent}  url = ${fmtString(node.props["url"] ?: "")},\n")
      if ("contentScale" in node.props) sb.append("${indent}  contentScale = ${fmtInt(node.props["contentScale"])},\n")
      if ("widthDp" in node.props) sb.append("${indent}  widthDp = ${fmtInt(node.props["widthDp"])},\n")
      if ("heightDp" in node.props) sb.append("${indent}  heightDp = ${fmtInt(node.props["heightDp"])},\n")
      if ("blurDp" in node.props) sb.append("${indent}  blurDp = ${fmtInt(node.props["blurDp"])},\n")
      if ("fillWidth" in node.props) sb.append("${indent}  fillWidth = ${fmtBool(node.props["fillWidth"])},\n")
      if ("tintArgb" in node.props) sb.append("${indent}  tintArgb = ${fmtInt(node.props["tintArgb"])},\n")
      sb.append("$indent)\n")
    }
    "Badge" -> {
      sb.append("${indent}Badge(\n")
      if ("text" in node.props) sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "BottomAppBar" -> {
      sb.append("${indent}BottomAppBar(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "BottomSheet" -> {
      sb.append("${indent}BottomSheet(\n")
      sb.append("${indent}  visible = ${fmtBool(node.props["visible"])},\n")
      if ("contentPaddingDp" in node.props) sb.append("${indent}  contentPaddingDp = ${fmtInt(node.props["contentPaddingDp"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Box" -> {
      sb.append("${indent}Box(\n")
      if ("width" in node.props) sb.append("${indent}  width = ${fmtConstraint(node.props["width"])},\n")
      if ("height" in node.props) sb.append("${indent}  height = ${fmtConstraint(node.props["height"])},\n")
      if ("horizontalAlignment" in node.props) sb.append("${indent}  horizontalAlignment = ${fmtCrossAxis(node.props["horizontalAlignment"])},\n")
      if ("verticalAlignment" in node.props) sb.append("${indent}  verticalAlignment = ${fmtCrossAxis(node.props["verticalAlignment"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Button" -> {
      sb.append("${indent}Button(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      if ("containerArgb" in node.props) sb.append("${indent}  containerArgb = ${fmtInt(node.props["containerArgb"])},\n")
      if ("contentArgb" in node.props) sb.append("${indent}  contentArgb = ${fmtInt(node.props["contentArgb"])},\n")
      if ("cornerRadiusDp" in node.props) sb.append("${indent}  cornerRadiusDp = ${fmtInt(node.props["cornerRadiusDp"])},\n")
      sb.append("$indent)\n")
    }
    "Card" -> {
      sb.append("${indent}Card(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Checkbox" -> {
      sb.append("${indent}Checkbox(\n")
      sb.append("${indent}  checked = ${fmtBool(node.props["checked"])},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      sb.append("$indent)\n")
    }
    "Chip" -> {
      sb.append("${indent}Chip(\n")
      sb.append("${indent}  label = ${fmtString(node.props["label"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "CircularProgressIndicator" -> {
      sb.append("${indent}CircularProgressIndicator(\n")
      if ("progress" in node.props) sb.append("${indent}  progress = ${fmtFloat(node.props["progress"])},\n")
      sb.append("$indent)\n")
    }
    "Clickable" -> {
      sb.append("${indent}Clickable(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Column" -> {
      sb.append("${indent}Column(\n")
      if ("width" in node.props) sb.append("${indent}  width = ${fmtConstraint(node.props["width"])},\n")
      if ("height" in node.props) sb.append("${indent}  height = ${fmtConstraint(node.props["height"])},\n")
      if ("overflow" in node.props) sb.append("${indent}  overflow = ${fmtOverflow(node.props["overflow"])},\n")
      if ("horizontalAlignment" in node.props) sb.append("${indent}  horizontalAlignment = ${fmtCrossAxis(node.props["horizontalAlignment"])},\n")
      if ("verticalAlignment" in node.props) sb.append("${indent}  verticalAlignment = ${fmtMainAxis(node.props["verticalAlignment"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Dialog" -> {
      sb.append("${indent}Dialog(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Divider" -> {
      sb.append("${indent}Divider(\n")
      if ("thickness" in node.props) sb.append("${indent}  thickness = ${fmtInt(node.props["thickness"])},\n")
      sb.append("$indent)\n")
    }
    "ElevatedButton" -> {
      sb.append("${indent}ElevatedButton(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      sb.append("$indent)\n")
    }
    "ElevatedCard" -> {
      sb.append("${indent}ElevatedCard(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "ExtendedFloatingActionButton" -> {
      sb.append("${indent}ExtendedFloatingActionButton(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "FilledTonalButton" -> {
      sb.append("${indent}FilledTonalButton(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      sb.append("$indent)\n")
    }
    "FilterChip" -> {
      sb.append("${indent}FilterChip(\n")
      sb.append("${indent}  label = ${fmtString(node.props["label"] ?: "")},\n")
      if ("selected" in node.props) sb.append("${indent}  selected = ${fmtBool(node.props["selected"])},\n")
      sb.append("$indent)\n")
    }
    "FloatingActionButton" -> {
      sb.append("${indent}FloatingActionButton(\n")
      if ("text" in node.props) sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "FlowColumn" -> {
      sb.append("${indent}FlowColumn(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "FlowRow" -> {
      sb.append("${indent}FlowRow(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "HorizontalPager" -> {
      sb.append("${indent}HorizontalPager(\n")
      if ("autoScrollMs" in node.props) sb.append("${indent}  autoScrollMs = ${fmtInt(node.props["autoScrollMs"])},\n")
      if ("showIndicator" in node.props) sb.append("${indent}  showIndicator = ${fmtBool(node.props["showIndicator"])},\n")
      if ("indicatorActiveArgb" in node.props) sb.append("${indent}  indicatorActiveArgb = ${fmtInt(node.props["indicatorActiveArgb"])},\n")
      if ("indicatorInactiveArgb" in node.props) sb.append("${indent}  indicatorInactiveArgb = ${fmtInt(node.props["indicatorInactiveArgb"])},\n")
      if ("contentPaddingDp" in node.props) sb.append("${indent}  contentPaddingDp = ${fmtInt(node.props["contentPaddingDp"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "IconButton" -> {
      sb.append("${indent}IconButton(\n")
      sb.append("${indent}  imageUrl = ${fmtString(node.props["imageUrl"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "Image" -> {
      sb.append("${indent}Image(\n")
      sb.append("${indent}  url = ${fmtString(node.props["url"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "InputChip" -> {
      sb.append("${indent}InputChip(\n")
      sb.append("${indent}  label = ${fmtString(node.props["label"] ?: "")},\n")
      if ("selected" in node.props) sb.append("${indent}  selected = ${fmtBool(node.props["selected"])},\n")
      sb.append("$indent)\n")
    }
    "LazyHorizontalGrid" -> {
      sb.append("${indent}LazyHorizontalGrid(\n")
      if ("rows" in node.props) sb.append("${indent}  rows = ${fmtInt(node.props["rows"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "LazyVerticalGrid" -> {
      sb.append("${indent}LazyVerticalGrid(\n")
      if ("columns" in node.props) sb.append("${indent}  columns = ${fmtInt(node.props["columns"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "LinearProgressIndicator" -> {
      sb.append("${indent}LinearProgressIndicator(\n")
      if ("progress" in node.props) sb.append("${indent}  progress = ${fmtFloat(node.props["progress"])},\n")
      sb.append("$indent)\n")
    }
    "NavigationBar" -> {
      sb.append("${indent}NavigationBar(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "NavigationRail" -> {
      sb.append("${indent}NavigationRail(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "OutlinedButton" -> {
      sb.append("${indent}OutlinedButton(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      if ("iconUrl" in node.props) sb.append("${indent}  iconUrl = ${fmtString(node.props["iconUrl"] ?: "")},\n")
      if ("iconSizeDp" in node.props) sb.append("${indent}  iconSizeDp = ${fmtInt(node.props["iconSizeDp"])},\n")
      if ("containerArgb" in node.props) sb.append("${indent}  containerArgb = ${fmtInt(node.props["containerArgb"])},\n")
      if ("contentArgb" in node.props) sb.append("${indent}  contentArgb = ${fmtInt(node.props["contentArgb"])},\n")
      if ("borderArgb" in node.props) sb.append("${indent}  borderArgb = ${fmtInt(node.props["borderArgb"])},\n")
      if ("cornerRadiusDp" in node.props) sb.append("${indent}  cornerRadiusDp = ${fmtInt(node.props["cornerRadiusDp"])},\n")
      sb.append("$indent)\n")
    }
    "OutlinedCard" -> {
      sb.append("${indent}OutlinedCard(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "OutlinedTextField" -> {
      sb.append("${indent}OutlinedTextField(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("placeholder" in node.props) sb.append("${indent}  placeholder = ${fmtString(node.props["placeholder"] ?: "")},\n")
      if ("label" in node.props) sb.append("${indent}  label = ${fmtString(node.props["label"] ?: "")},\n")
      if ("leadingText" in node.props) sb.append("${indent}  leadingText = ${fmtString(node.props["leadingText"] ?: "")},\n")
      if ("keyboardType" in node.props) sb.append("${indent}  keyboardType = ${fmtInt(node.props["keyboardType"])},\n")
      if ("singleLine" in node.props) sb.append("${indent}  singleLine = ${fmtBool(node.props["singleLine"])},\n")
      if ("maxLines" in node.props) sb.append("${indent}  maxLines = ${fmtInt(node.props["maxLines"])},\n")
      if ("isError" in node.props) sb.append("${indent}  isError = ${fmtBool(node.props["isError"])},\n")
      if ("supportingText" in node.props) sb.append("${indent}  supportingText = ${fmtString(node.props["supportingText"] ?: "")},\n")
      if ("borderArgb" in node.props) sb.append("${indent}  borderArgb = ${fmtInt(node.props["borderArgb"])},\n")
      if ("cornerRadiusDp" in node.props) sb.append("${indent}  cornerRadiusDp = ${fmtInt(node.props["cornerRadiusDp"])},\n")
      sb.append("$indent)\n")
    }
    "RadioButton" -> {
      sb.append("${indent}RadioButton(\n")
      sb.append("${indent}  selected = ${fmtBool(node.props["selected"])},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      sb.append("$indent)\n")
    }
    "Row" -> {
      sb.append("${indent}Row(\n")
      if ("width" in node.props) sb.append("${indent}  width = ${fmtConstraint(node.props["width"])},\n")
      if ("height" in node.props) sb.append("${indent}  height = ${fmtConstraint(node.props["height"])},\n")
      if ("overflow" in node.props) sb.append("${indent}  overflow = ${fmtOverflow(node.props["overflow"])},\n")
      if ("horizontalAlignment" in node.props) sb.append("${indent}  horizontalAlignment = ${fmtMainAxis(node.props["horizontalAlignment"])},\n")
      if ("verticalAlignment" in node.props) sb.append("${indent}  verticalAlignment = ${fmtCrossAxis(node.props["verticalAlignment"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "ScrollableColumn" -> {
      sb.append("${indent}ScrollableColumn(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Shimmer" -> {
      sb.append("${indent}Shimmer(\n")
      if ("widthDp" in node.props) sb.append("${indent}  widthDp = ${fmtInt(node.props["widthDp"])},\n")
      if ("heightDp" in node.props) sb.append("${indent}  heightDp = ${fmtInt(node.props["heightDp"])},\n")
      if ("cornerRadiusDp" in node.props) sb.append("${indent}  cornerRadiusDp = ${fmtInt(node.props["cornerRadiusDp"])},\n")
      sb.append("$indent)\n")
    }
    "Slider" -> {
      sb.append("${indent}Slider(\n")
      if ("position" in node.props) sb.append("${indent}  position = ${fmtFloat(node.props["position"])},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      sb.append("$indent)\n")
    }
    "Snackbar" -> {
      sb.append("${indent}Snackbar(\n")
      sb.append("${indent}  message = ${fmtString(node.props["message"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "Spacer" -> {
      sb.append("${indent}Spacer(\n")
      if ("width" in node.props) sb.append("${indent}  width = ${fmtDp(node.props["width"])},\n")
      if ("height" in node.props) sb.append("${indent}  height = ${fmtDp(node.props["height"])},\n")
      sb.append("$indent)\n")
    }
    "StyledBox" -> {
      sb.append("${indent}StyledBox(\n")
      if ("colorArgb" in node.props) sb.append("${indent}  colorArgb = ${fmtInt(node.props["colorArgb"])},\n")
      if ("gradientStartArgb" in node.props) sb.append("${indent}  gradientStartArgb = ${fmtInt(node.props["gradientStartArgb"])},\n")
      if ("gradientEndArgb" in node.props) sb.append("${indent}  gradientEndArgb = ${fmtInt(node.props["gradientEndArgb"])},\n")
      if ("cornerRadiusDp" in node.props) sb.append("${indent}  cornerRadiusDp = ${fmtInt(node.props["cornerRadiusDp"])},\n")
      if ("widthDp" in node.props) sb.append("${indent}  widthDp = ${fmtInt(node.props["widthDp"])},\n")
      if ("heightDp" in node.props) sb.append("${indent}  heightDp = ${fmtInt(node.props["heightDp"])},\n")
      if ("paddingDp" in node.props) sb.append("${indent}  paddingDp = ${fmtInt(node.props["paddingDp"])},\n")
      if ("fillWidth" in node.props) sb.append("${indent}  fillWidth = ${fmtBool(node.props["fillWidth"])},\n")
      if ("contentAlignment" in node.props) sb.append("${indent}  contentAlignment = ${fmtInt(node.props["contentAlignment"])},\n")
      if ("offsetYDp" in node.props) sb.append("${indent}  offsetYDp = ${fmtInt(node.props["offsetYDp"])},\n")
      if ("elevationDp" in node.props) sb.append("${indent}  elevationDp = ${fmtInt(node.props["elevationDp"])},\n")
      if ("borderColorArgb" in node.props) sb.append("${indent}  borderColorArgb = ${fmtInt(node.props["borderColorArgb"])},\n")
      if ("borderWidthDp" in node.props) sb.append("${indent}  borderWidthDp = ${fmtInt(node.props["borderWidthDp"])},\n")
      if ("gradientVertical" in node.props) sb.append("${indent}  gradientVertical = ${fmtBool(node.props["gradientVertical"])},\n")
      if ("gradientColorsArgb" in node.props) sb.append("${indent}  gradientColorsArgb = ${fmtIntList(node.props["gradientColorsArgb"])},\n")
      if ("gradientStops" in node.props) sb.append("${indent}  gradientStops = ${fmtFloatList(node.props["gradientStops"])},\n")
      if ("gradientDirection" in node.props) sb.append("${indent}  gradientDirection = ${fmtInt(node.props["gradientDirection"])},\n")
      if ("cornerTopStartDp" in node.props) sb.append("${indent}  cornerTopStartDp = ${fmtInt(node.props["cornerTopStartDp"])},\n")
      if ("cornerTopEndDp" in node.props) sb.append("${indent}  cornerTopEndDp = ${fmtInt(node.props["cornerTopEndDp"])},\n")
      if ("cornerBottomStartDp" in node.props) sb.append("${indent}  cornerBottomStartDp = ${fmtInt(node.props["cornerBottomStartDp"])},\n")
      if ("cornerBottomEndDp" in node.props) sb.append("${indent}  cornerBottomEndDp = ${fmtInt(node.props["cornerBottomEndDp"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "StyledText" -> {
      sb.append("${indent}StyledText(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("fontSize" in node.props) sb.append("${indent}  fontSize = ${fmtInt(node.props["fontSize"])},\n")
      if ("bold" in node.props) sb.append("${indent}  bold = ${fmtBool(node.props["bold"])},\n")
      if ("colorArgb" in node.props) sb.append("${indent}  colorArgb = ${fmtInt(node.props["colorArgb"])},\n")
      if ("align" in node.props) sb.append("${indent}  align = ${fmtInt(node.props["align"])},\n")
      if ("maxLines" in node.props) sb.append("${indent}  maxLines = ${fmtInt(node.props["maxLines"])},\n")
      if ("overflow" in node.props) sb.append("${indent}  overflow = ${fmtInt(node.props["overflow"])},\n")
      if ("lineHeightSp" in node.props) sb.append("${indent}  lineHeightSp = ${fmtInt(node.props["lineHeightSp"])},\n")
      if ("letterSpacingX100" in node.props) sb.append("${indent}  letterSpacingX100 = ${fmtInt(node.props["letterSpacingX100"])},\n")
      if ("italic" in node.props) sb.append("${indent}  italic = ${fmtBool(node.props["italic"])},\n")
      if ("underline" in node.props) sb.append("${indent}  underline = ${fmtBool(node.props["underline"])},\n")
      if ("strikethrough" in node.props) sb.append("${indent}  strikethrough = ${fmtBool(node.props["strikethrough"])},\n")
      if ("weight" in node.props) sb.append("${indent}  weight = ${fmtInt(node.props["weight"])},\n")
      if ("colorRole" in node.props) sb.append("${indent}  colorRole = ${fmtInt(node.props["colorRole"])},\n")
      sb.append("$indent)\n")
    }
    "SuggestionChip" -> {
      sb.append("${indent}SuggestionChip(\n")
      sb.append("${indent}  label = ${fmtString(node.props["label"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "Surface" -> {
      sb.append("${indent}Surface(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Switch" -> {
      sb.append("${indent}Switch(\n")
      sb.append("${indent}  checked = ${fmtBool(node.props["checked"])},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      sb.append("$indent)\n")
    }
    "Tab" -> {
      sb.append("${indent}Tab(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("selected" in node.props) sb.append("${indent}  selected = ${fmtBool(node.props["selected"])},\n")
      sb.append("$indent)\n")
    }
    "TabRow" -> {
      sb.append("${indent}TabRow(\n")
      if ("selectedIndex" in node.props) sb.append("${indent}  selectedIndex = ${fmtInt(node.props["selectedIndex"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Text" -> {
      sb.append("${indent}Text(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "TextButton" -> {
      sb.append("${indent}TextButton(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("enabled" in node.props) sb.append("${indent}  enabled = ${fmtBool(node.props["enabled"])},\n")
      sb.append("$indent)\n")
    }
    "TextField" -> {
      sb.append("${indent}TextField(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      if ("placeholder" in node.props) sb.append("${indent}  placeholder = ${fmtString(node.props["placeholder"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "TextInput" -> {
      sb.append("${indent}TextInput(\n")
      if ("hint" in node.props) sb.append("${indent}  hint = ${fmtString(node.props["hint"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "Theme" -> {
      sb.append("${indent}Theme(\n")
      if ("dark" in node.props) sb.append("${indent}  dark = ${fmtBool(node.props["dark"])},\n")
      if ("primaryArgb" in node.props) sb.append("${indent}  primaryArgb = ${fmtInt(node.props["primaryArgb"])},\n")
      if ("onPrimaryArgb" in node.props) sb.append("${indent}  onPrimaryArgb = ${fmtInt(node.props["onPrimaryArgb"])},\n")
      if ("secondaryArgb" in node.props) sb.append("${indent}  secondaryArgb = ${fmtInt(node.props["secondaryArgb"])},\n")
      if ("onSecondaryArgb" in node.props) sb.append("${indent}  onSecondaryArgb = ${fmtInt(node.props["onSecondaryArgb"])},\n")
      if ("surfaceArgb" in node.props) sb.append("${indent}  surfaceArgb = ${fmtInt(node.props["surfaceArgb"])},\n")
      if ("onSurfaceArgb" in node.props) sb.append("${indent}  onSurfaceArgb = ${fmtInt(node.props["onSurfaceArgb"])},\n")
      if ("surfaceVariantArgb" in node.props) sb.append("${indent}  surfaceVariantArgb = ${fmtInt(node.props["surfaceVariantArgb"])},\n")
      if ("onSurfaceVariantArgb" in node.props) sb.append("${indent}  onSurfaceVariantArgb = ${fmtInt(node.props["onSurfaceVariantArgb"])},\n")
      if ("backgroundArgb" in node.props) sb.append("${indent}  backgroundArgb = ${fmtInt(node.props["backgroundArgb"])},\n")
      if ("onBackgroundArgb" in node.props) sb.append("${indent}  onBackgroundArgb = ${fmtInt(node.props["onBackgroundArgb"])},\n")
      if ("errorArgb" in node.props) sb.append("${indent}  errorArgb = ${fmtInt(node.props["errorArgb"])},\n")
      if ("outlineArgb" in node.props) sb.append("${indent}  outlineArgb = ${fmtInt(node.props["outlineArgb"])},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "Tooltip" -> {
      sb.append("${indent}Tooltip(\n")
      sb.append("${indent}  text = ${fmtString(node.props["text"] ?: "")},\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    "TopAppBar" -> {
      sb.append("${indent}TopAppBar(\n")
      sb.append("${indent}  title = ${fmtString(node.props["title"] ?: "")},\n")
      sb.append("$indent)\n")
    }
    "VerticalDivider" -> {
      sb.append("${indent}VerticalDivider(\n")
      if ("thickness" in node.props) sb.append("${indent}  thickness = ${fmtInt(node.props["thickness"])},\n")
      sb.append("$indent)\n")
    }
    "VerticalPager" -> {
      sb.append("${indent}VerticalPager(\n")
      sb.append("$indent) {\n")
      node.children.forEach { emitNode(sb, it, "$indent  ") }
      sb.append("$indent}\n")
    }
    else -> sb.append("$indent// unknown widget: ${node.type}\n")
  }
}
