// GENERATED by :portal-schema-codegen — do not edit. Run ./gradlew :portal-schema-codegen:generatePortalCode
package dev.keliver.portal

val widgetSpecs: List<WidgetSpec> = listOf(
  WidgetSpec("AlertDialog", "Material", listOf(
    PropSpec("title", PropKind.Text, "Title"),
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("confirmText", PropKind.Text, "Confirm text"),
    PropSpec("dismissText", PropKind.Text, "Dismiss text"),
  ), acceptsChildren = false, sampleProps = mapOf("title" to "New AlertDialog", "text" to "New AlertDialog"), events = listOf("onConfirm", "onDismiss")),
  WidgetSpec("AnimatedBorder", "Material", listOf(
    PropSpec("cornerRadiusDp", PropKind.Int, "Corner radius dp"),
    PropSpec("strokeWidthDp", PropKind.Int, "Stroke width dp"),
    PropSpec("baseColorArgb", PropKind.Color, "Base color argb"),
    PropSpec("cometColorArgb", PropKind.Color, "Comet color argb"),
    PropSpec("durationMs", PropKind.Int, "Duration ms"),
    PropSpec("segmentLenDp", PropKind.Int, "Segment len dp"),
    PropSpec("effect", PropKind.Int, "Effect"),
    PropSpec("colorsArgb", PropKind.IntList, "Colors argb"),
  ), acceptsChildren = true, sampleProps = emptyMap(), events = listOf("onClick")),
  WidgetSpec("AnimatedVisibility", "Material", listOf(
    PropSpec("visible", PropKind.Bool, "Visible"),
  ), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("AsyncImage", "Material", listOf(
    PropSpec("url", PropKind.Text, "Url"),
    PropSpec("contentScale", PropKind.Int, "Content scale"),
    PropSpec("widthDp", PropKind.Int, "Width dp"),
    PropSpec("heightDp", PropKind.Int, "Height dp"),
    PropSpec("blurDp", PropKind.Int, "Blur dp"),
    PropSpec("fillWidth", PropKind.Bool, "Fill width"),
    PropSpec("tintArgb", PropKind.Color, "Tint argb"),
  ), acceptsChildren = false, sampleProps = mapOf("url" to "New AsyncImage"), events = listOf("onClick")),
  WidgetSpec("Badge", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
  ), acceptsChildren = false, sampleProps = emptyMap()),
  WidgetSpec("BottomAppBar", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("BottomSheet", "Material", listOf(
    PropSpec("visible", PropKind.Bool, "Visible"),
    PropSpec("contentPaddingDp", PropKind.Int, "Content padding dp"),
  ), acceptsChildren = true, sampleProps = mapOf("visible" to false), events = listOf("onDismiss")),
  WidgetSpec("Box", "Layout", listOf(
    PropSpec("width", PropKind.Int, "Width"),
    PropSpec("height", PropKind.Int, "Height"),
    PropSpec("horizontalAlignment", PropKind.Int, "Horizontal alignment"),
    PropSpec("verticalAlignment", PropKind.Int, "Vertical alignment"),
  ), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("Button", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
    PropSpec("containerArgb", PropKind.Color, "Container argb"),
    PropSpec("contentArgb", PropKind.Color, "Content argb"),
    PropSpec("cornerRadiusDp", PropKind.Int, "Corner radius dp"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New Button"), events = listOf("onClick")),
  WidgetSpec("Card", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("Checkbox", "Material", listOf(
    PropSpec("checked", PropKind.Bool, "Checked"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
  ), acceptsChildren = false, sampleProps = mapOf("checked" to false), events = listOf("onCheckedChange")),
  WidgetSpec("Chip", "Material", listOf(
    PropSpec("label", PropKind.Text, "Label"),
  ), acceptsChildren = false, sampleProps = mapOf("label" to "New Chip"), events = listOf("onClick")),
  WidgetSpec("CircularProgressIndicator", "Material", listOf(
    PropSpec("progress", PropKind.Double, "Progress"),
  ), acceptsChildren = false, sampleProps = emptyMap()),
  WidgetSpec("Clickable", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap(), events = listOf("onClick")),
  WidgetSpec("Column", "Layout", listOf(
    PropSpec("width", PropKind.Int, "Width"),
    PropSpec("height", PropKind.Int, "Height"),
    PropSpec("overflow", PropKind.Int, "Overflow"),
    PropSpec("horizontalAlignment", PropKind.Int, "Horizontal alignment"),
    PropSpec("verticalAlignment", PropKind.Int, "Vertical alignment"),
  ), acceptsChildren = true, sampleProps = emptyMap(), events = listOf("onScroll")),
  WidgetSpec("Dialog", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap(), events = listOf("onDismiss")),
  WidgetSpec("Divider", "Material", listOf(
    PropSpec("thickness", PropKind.Int, "Thickness"),
  ), acceptsChildren = false, sampleProps = emptyMap()),
  WidgetSpec("DropdownMenu", "Material", listOf(
    PropSpec("expanded", PropKind.Bool, "Expanded"),
    PropSpec("options", PropKind.StringList, "Options"),
  ), acceptsChildren = false, sampleProps = mapOf("options" to listOf("Option A", "Option B")), events = listOf("onSelect", "onDismiss")),
  WidgetSpec("ElevatedButton", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New ElevatedButton"), events = listOf("onClick")),
  WidgetSpec("ElevatedCard", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("ExtendedFloatingActionButton", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New ExtendedFloatingActionButton"), events = listOf("onClick")),
  WidgetSpec("FilledTonalButton", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New FilledTonalButton"), events = listOf("onClick")),
  WidgetSpec("FilterChip", "Material", listOf(
    PropSpec("label", PropKind.Text, "Label"),
    PropSpec("selected", PropKind.Bool, "Selected"),
  ), acceptsChildren = false, sampleProps = mapOf("label" to "New FilterChip"), events = listOf("onClick")),
  WidgetSpec("FloatingActionButton", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
  ), acceptsChildren = false, sampleProps = emptyMap(), events = listOf("onClick")),
  WidgetSpec("FlowColumn", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("FlowRow", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("HorizontalPager", "Material", listOf(
    PropSpec("autoScrollMs", PropKind.Int, "Auto scroll ms"),
    PropSpec("showIndicator", PropKind.Bool, "Show indicator"),
    PropSpec("indicatorActiveArgb", PropKind.Color, "Indicator active argb"),
    PropSpec("indicatorInactiveArgb", PropKind.Color, "Indicator inactive argb"),
    PropSpec("contentPaddingDp", PropKind.Int, "Content padding dp"),
  ), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("IconButton", "Material", listOf(
    PropSpec("imageUrl", PropKind.Text, "Image url"),
  ), acceptsChildren = false, sampleProps = mapOf("imageUrl" to "New IconButton"), events = listOf("onClick")),
  WidgetSpec("Image", "Material", listOf(
    PropSpec("url", PropKind.Text, "Url"),
  ), acceptsChildren = false, sampleProps = mapOf("url" to "New Image"), events = listOf("onClick")),
  WidgetSpec("InputChip", "Material", listOf(
    PropSpec("label", PropKind.Text, "Label"),
    PropSpec("selected", PropKind.Bool, "Selected"),
  ), acceptsChildren = false, sampleProps = mapOf("label" to "New InputChip"), events = listOf("onClick")),
  WidgetSpec("LazyHorizontalGrid", "Material", listOf(
    PropSpec("rows", PropKind.Int, "Rows"),
  ), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("LazyVerticalGrid", "Material", listOf(
    PropSpec("columns", PropKind.Int, "Columns"),
  ), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("LinearProgressIndicator", "Material", listOf(
    PropSpec("progress", PropKind.Double, "Progress"),
  ), acceptsChildren = false, sampleProps = emptyMap()),
  WidgetSpec("NavigationBar", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("NavigationRail", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("OutlinedButton", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
    PropSpec("iconUrl", PropKind.Text, "Icon url"),
    PropSpec("iconSizeDp", PropKind.Int, "Icon size dp"),
    PropSpec("containerArgb", PropKind.Color, "Container argb"),
    PropSpec("contentArgb", PropKind.Color, "Content argb"),
    PropSpec("borderArgb", PropKind.Color, "Border argb"),
    PropSpec("cornerRadiusDp", PropKind.Int, "Corner radius dp"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New OutlinedButton"), events = listOf("onClick")),
  WidgetSpec("OutlinedCard", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("OutlinedTextField", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("placeholder", PropKind.Text, "Placeholder"),
    PropSpec("label", PropKind.Text, "Label"),
    PropSpec("leadingText", PropKind.Text, "Leading text"),
    PropSpec("keyboardType", PropKind.Int, "Keyboard type"),
    PropSpec("singleLine", PropKind.Bool, "Single line"),
    PropSpec("maxLines", PropKind.Int, "Max lines"),
    PropSpec("isError", PropKind.Bool, "Is error"),
    PropSpec("supportingText", PropKind.Text, "Supporting text"),
    PropSpec("borderArgb", PropKind.Color, "Border argb"),
    PropSpec("cornerRadiusDp", PropKind.Int, "Corner radius dp"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New OutlinedTextField"), events = listOf("onValueChange")),
  WidgetSpec("RadioButton", "Material", listOf(
    PropSpec("selected", PropKind.Bool, "Selected"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
  ), acceptsChildren = false, sampleProps = mapOf("selected" to false), events = listOf("onClick")),
  WidgetSpec("Row", "Layout", listOf(
    PropSpec("width", PropKind.Int, "Width"),
    PropSpec("height", PropKind.Int, "Height"),
    PropSpec("overflow", PropKind.Int, "Overflow"),
    PropSpec("horizontalAlignment", PropKind.Int, "Horizontal alignment"),
    PropSpec("verticalAlignment", PropKind.Int, "Vertical alignment"),
  ), acceptsChildren = true, sampleProps = emptyMap(), events = listOf("onScroll")),
  WidgetSpec("ScrollableColumn", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("SegmentedButtonRow", "Material", listOf(
    PropSpec("options", PropKind.StringList, "Options"),
    PropSpec("selectedIndex", PropKind.Int, "Selected index"),
  ), acceptsChildren = false, sampleProps = mapOf("options" to listOf("Option A", "Option B")), events = listOf("onSelect")),
  WidgetSpec("Shimmer", "Material", listOf(
    PropSpec("widthDp", PropKind.Int, "Width dp"),
    PropSpec("heightDp", PropKind.Int, "Height dp"),
    PropSpec("cornerRadiusDp", PropKind.Int, "Corner radius dp"),
  ), acceptsChildren = false, sampleProps = emptyMap()),
  WidgetSpec("Slider", "Material", listOf(
    PropSpec("position", PropKind.Double, "Position"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
  ), acceptsChildren = false, sampleProps = emptyMap(), events = listOf("onValueChange")),
  WidgetSpec("Snackbar", "Material", listOf(
    PropSpec("message", PropKind.Text, "Message"),
  ), acceptsChildren = false, sampleProps = mapOf("message" to "New Snackbar")),
  WidgetSpec("Spacer", "Layout", listOf(
    PropSpec("width", PropKind.Double, "Width"),
    PropSpec("height", PropKind.Double, "Height"),
  ), acceptsChildren = false, sampleProps = emptyMap()),
  WidgetSpec("StyledBox", "Material", listOf(
    PropSpec("colorArgb", PropKind.Color, "Color argb"),
    PropSpec("gradientStartArgb", PropKind.Color, "Gradient start argb"),
    PropSpec("gradientEndArgb", PropKind.Color, "Gradient end argb"),
    PropSpec("cornerRadiusDp", PropKind.Int, "Corner radius dp"),
    PropSpec("widthDp", PropKind.Int, "Width dp"),
    PropSpec("heightDp", PropKind.Int, "Height dp"),
    PropSpec("paddingDp", PropKind.Int, "Padding dp"),
    PropSpec("fillWidth", PropKind.Bool, "Fill width"),
    PropSpec("contentAlignment", PropKind.Int, "Content alignment"),
    PropSpec("offsetYDp", PropKind.Int, "Offset ydp"),
    PropSpec("elevationDp", PropKind.Int, "Elevation dp"),
    PropSpec("borderColorArgb", PropKind.Color, "Border color argb"),
    PropSpec("borderWidthDp", PropKind.Int, "Border width dp"),
    PropSpec("gradientVertical", PropKind.Bool, "Gradient vertical"),
    PropSpec("gradientColorsArgb", PropKind.IntList, "Gradient colors argb"),
    PropSpec("gradientStops", PropKind.FloatList, "Gradient stops"),
    PropSpec("gradientDirection", PropKind.Int, "Gradient direction"),
    PropSpec("cornerTopStartDp", PropKind.Int, "Corner top start dp"),
    PropSpec("cornerTopEndDp", PropKind.Int, "Corner top end dp"),
    PropSpec("cornerBottomStartDp", PropKind.Int, "Corner bottom start dp"),
    PropSpec("cornerBottomEndDp", PropKind.Int, "Corner bottom end dp"),
  ), acceptsChildren = true, sampleProps = emptyMap(), events = listOf("onClick")),
  WidgetSpec("StyledText", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("fontSize", PropKind.Int, "Font size"),
    PropSpec("bold", PropKind.Bool, "Bold"),
    PropSpec("colorArgb", PropKind.Color, "Color argb"),
    PropSpec("align", PropKind.Int, "Align"),
    PropSpec("maxLines", PropKind.Int, "Max lines"),
    PropSpec("overflow", PropKind.Int, "Overflow"),
    PropSpec("lineHeightSp", PropKind.Int, "Line height sp"),
    PropSpec("letterSpacingX100", PropKind.Int, "Letter spacing x100"),
    PropSpec("italic", PropKind.Bool, "Italic"),
    PropSpec("underline", PropKind.Bool, "Underline"),
    PropSpec("strikethrough", PropKind.Bool, "Strikethrough"),
    PropSpec("weight", PropKind.Int, "Weight"),
    PropSpec("colorRole", PropKind.Int, "Color role"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New StyledText")),
  WidgetSpec("SuggestionChip", "Material", listOf(
    PropSpec("label", PropKind.Text, "Label"),
  ), acceptsChildren = false, sampleProps = mapOf("label" to "New SuggestionChip"), events = listOf("onClick")),
  WidgetSpec("Surface", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("Switch", "Material", listOf(
    PropSpec("checked", PropKind.Bool, "Checked"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
  ), acceptsChildren = false, sampleProps = mapOf("checked" to false), events = listOf("onCheckedChange")),
  WidgetSpec("Tab", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("selected", PropKind.Bool, "Selected"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New Tab"), events = listOf("onClick")),
  WidgetSpec("TabRow", "Material", listOf(
    PropSpec("selectedIndex", PropKind.Int, "Selected index"),
  ), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("Text", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New Text")),
  WidgetSpec("TextButton", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("enabled", PropKind.Bool, "Enabled"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New TextButton"), events = listOf("onClick")),
  WidgetSpec("TextField", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
    PropSpec("placeholder", PropKind.Text, "Placeholder"),
  ), acceptsChildren = false, sampleProps = mapOf("text" to "New TextField"), events = listOf("onValueChange")),
  WidgetSpec("TextInput", "Material", listOf(
    PropSpec("hint", PropKind.Text, "Hint"),
  ), acceptsChildren = false, sampleProps = emptyMap(), events = listOf("onChange")),
  WidgetSpec("Theme", "Material", listOf(
    PropSpec("dark", PropKind.Bool, "Dark"),
    PropSpec("primaryArgb", PropKind.Color, "Primary argb"),
    PropSpec("onPrimaryArgb", PropKind.Color, "On primary argb"),
    PropSpec("secondaryArgb", PropKind.Color, "Secondary argb"),
    PropSpec("onSecondaryArgb", PropKind.Color, "On secondary argb"),
    PropSpec("surfaceArgb", PropKind.Color, "Surface argb"),
    PropSpec("onSurfaceArgb", PropKind.Color, "On surface argb"),
    PropSpec("surfaceVariantArgb", PropKind.Color, "Surface variant argb"),
    PropSpec("onSurfaceVariantArgb", PropKind.Color, "On surface variant argb"),
    PropSpec("backgroundArgb", PropKind.Color, "Background argb"),
    PropSpec("onBackgroundArgb", PropKind.Color, "On background argb"),
    PropSpec("errorArgb", PropKind.Color, "Error argb"),
    PropSpec("outlineArgb", PropKind.Color, "Outline argb"),
  ), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("Tooltip", "Material", listOf(
    PropSpec("text", PropKind.Text, "Text"),
  ), acceptsChildren = true, sampleProps = mapOf("text" to "New Tooltip")),
  WidgetSpec("TopAppBar", "Material", listOf(
    PropSpec("title", PropKind.Text, "Title"),
  ), acceptsChildren = false, sampleProps = mapOf("title" to "New TopAppBar")),
  WidgetSpec("VerticalDivider", "Material", listOf(
    PropSpec("thickness", PropKind.Int, "Thickness"),
  ), acceptsChildren = false, sampleProps = emptyMap()),
  WidgetSpec("VerticalPager", "Material", listOf(), acceptsChildren = true, sampleProps = emptyMap()),
  WidgetSpec("Condition", "Logic", listOf(PropSpec("field", PropKind.Text, "If field (Boolean)")), acceptsChildren = true, sampleProps = mapOf("field" to "showThis")),
  WidgetSpec("Repeat", "Logic", listOf(PropSpec("items", PropKind.Text, "Items field (List)"), PropSpec("item", PropKind.Text, "Item name")), acceptsChildren = true, sampleProps = mapOf("items" to "items", "item" to "item")),
)

val modifierSpecs: List<ModifierSpec> = listOf(
  ModifierSpec("Alpha", listOf(PropSpec("pct", PropKind.Int, "Pct"))),
  ModifierSpec("AnimateContentSize", listOf()),
  ModifierSpec("AspectRatio", listOf(PropSpec("ratio", PropKind.Double, "Ratio"))),
  ModifierSpec("Background", listOf(PropSpec("colorArgb", PropKind.Color, "Color argb"))),
  ModifierSpec("Blur", listOf(PropSpec("radiusDp", PropKind.Int, "Radius dp"))),
  ModifierSpec("Border", listOf(PropSpec("widthDp", PropKind.Int, "Width dp"), PropSpec("colorArgb", PropKind.Color, "Color argb"))),
  ModifierSpec("CornerRadius", listOf(PropSpec("radiusDp", PropKind.Int, "Radius dp"))),
  ModifierSpec("CornerRadiusEach", listOf(PropSpec("topStartDp", PropKind.Int, "Top start dp"), PropSpec("topEndDp", PropKind.Int, "Top end dp"), PropSpec("bottomEndDp", PropKind.Int, "Bottom end dp"), PropSpec("bottomStartDp", PropKind.Int, "Bottom start dp"))),
  ModifierSpec("FillMaxHeight", listOf()),
  ModifierSpec("FillMaxSize", listOf()),
  ModifierSpec("FillWidth", listOf()),
  ModifierSpec("GradientBackground", listOf(PropSpec("startArgb", PropKind.Color, "Start argb"), PropSpec("endArgb", PropKind.Color, "End argb"))),
  ModifierSpec("Offset", listOf(PropSpec("xDp", PropKind.Int, "X dp"), PropSpec("yDp", PropKind.Int, "Y dp"))),
  ModifierSpec("Padding", listOf(PropSpec("allDp", PropKind.Int, "All dp"))),
  ModifierSpec("PaddingEach", listOf(PropSpec("startDp", PropKind.Int, "Start dp"), PropSpec("topDp", PropKind.Int, "Top dp"), PropSpec("endDp", PropKind.Int, "End dp"), PropSpec("bottomDp", PropKind.Int, "Bottom dp"))),
  ModifierSpec("Rotate", listOf(PropSpec("degrees", PropKind.Int, "Degrees"))),
  ModifierSpec("Scale", listOf(PropSpec("percent", PropKind.Int, "Percent"))),
  ModifierSpec("Shadow", listOf(PropSpec("elevationDp", PropKind.Int, "Elevation dp"))),
  ModifierSpec("Size", listOf(PropSpec("widthDp", PropKind.Int, "Width dp"), PropSpec("heightDp", PropKind.Int, "Height dp"))),
)

private val specsByType = widgetSpecs.associateBy { it.type }

fun widgetSpec(type: String): WidgetSpec? = specsByType[type]

fun editableProps(type: String): List<PropSpec> = specsByType[type]?.props ?: emptyList()
