/*
 * Copyright (C) 2026 Konduit contributors.
 * Licensed under the Apache License, Version 2.0.
 */
package dev.konduit.sample.host

import androidx.compose.foundation.layout.Box as ComposeBox
import androidx.compose.material.Text as ComposeText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier as ComposeModifier
import dev.konduit.sample.schema.widget.Box
import dev.konduit.sample.schema.widget.SampleSchemaWidgetFactory
import dev.konduit.sample.schema.widget.Text
import dev.konduit.widget.Widget
import dev.konduit.widget.compose.ComposeWidgetChildren

/**
 * Host-side renderer signature. Every widget impl provides a `value`
 * of this type — a Composable that paints itself into the host's
 * Compose tree, given an incoming Modifier from the parent.
 *
 * The `WidgetSystem` Konduit hands to `TreehouseContent` is
 * parameterized over this signature; that's how the host plugs in
 * its rendering layer without Konduit having to know about Compose.
 */
public typealias CmpRender = @Composable (ComposeModifier) -> Unit

/**
 * Binds each codegen'd widget interface in the schema to a concrete
 * Compose impl. `SampleSchemaWidgetFactory` is generated by
 * `:shared-widget` from the `@Schema` declaration — adding a new
 * widget there means adding a new `override fun Foo()` here.
 *
 * `WidgetSystem` then wraps this factory and the rest of the
 * protocol machinery (children-slot routing, modifier decoding, etc.)
 * for `TreehouseContent` to consume.
 */
public object CmpWidgetFactory : SampleSchemaWidgetFactory<CmpRender> {
  override fun Box(): Box<CmpRender> = CmpBox()
  override fun Text(): Text<CmpRender> = CmpText()
}

/**
 * `Box` impl. A single `Children(1)` slot in the schema becomes a
 * `Widget.Children<CmpRender>` here — Konduit injects the host's
 * `ComposeWidgetChildren` so the guest's child widgets get rendered
 * inside the Compose Box layout.
 */
private class CmpBox : Box<CmpRender> {
  override val children: Widget.Children<CmpRender> = ComposeWidgetChildren()
  override var modifier: dev.konduit.Modifier = dev.konduit.Modifier

  override val value: CmpRender = { incoming ->
    ComposeBox(modifier = incoming) {
      (children as ComposeWidgetChildren).Render()
    }
  }
}

/**
 * `Text` impl. The `@Property(1) text` from the schema becomes the
 * `text(value: String)` setter override below. Compose's
 * `mutableStateOf` makes recomposition automatic when the guest
 * updates the value.
 */
private class CmpText : Text<CmpRender> {
  private var textValue by mutableStateOf("")
  override var modifier: dev.konduit.Modifier = dev.konduit.Modifier

  override val value: CmpRender = { incoming ->
    ComposeText(text = textValue, modifier = incoming)
  }

  override fun text(text: String) {
    textValue = text
  }
}
