// GENERATED by :portal-schema-codegen — do not edit. Run ./gradlew :portal-schema-codegen:generatePortalCode
package dev.keliver.portal.render

import androidx.compose.runtime.Composable
import dev.keliver.Modifier
import dev.keliver.portal.WidgetNode
import dev.keliver.portal.bool
import dev.keliver.portal.floatList
import dev.keliver.portal.intList
import dev.keliver.ui.Dp
import dev.keliver.material.compose.AlertDialog
import dev.keliver.material.compose.AnimatedBorder
import dev.keliver.material.compose.AnimatedVisibility
import dev.keliver.material.compose.AsyncImage
import dev.keliver.material.compose.Badge
import dev.keliver.material.compose.BottomAppBar
import dev.keliver.material.compose.BottomSheet
import dev.keliver.layout.compose.Box
import dev.keliver.material.compose.Button
import dev.keliver.material.compose.Card
import dev.keliver.material.compose.Checkbox
import dev.keliver.material.compose.Chip
import dev.keliver.material.compose.CircularProgressIndicator
import dev.keliver.material.compose.Clickable
import dev.keliver.layout.compose.Column
import dev.keliver.material.compose.Dialog
import dev.keliver.material.compose.Divider
import dev.keliver.material.compose.ElevatedButton
import dev.keliver.material.compose.ElevatedCard
import dev.keliver.material.compose.ExtendedFloatingActionButton
import dev.keliver.material.compose.FilledTonalButton
import dev.keliver.material.compose.FilterChip
import dev.keliver.material.compose.FloatingActionButton
import dev.keliver.material.compose.FlowColumn
import dev.keliver.material.compose.FlowRow
import dev.keliver.material.compose.HorizontalPager
import dev.keliver.material.compose.IconButton
import dev.keliver.material.compose.Image
import dev.keliver.material.compose.InputChip
import dev.keliver.material.compose.LazyHorizontalGrid
import dev.keliver.material.compose.LazyVerticalGrid
import dev.keliver.material.compose.LinearProgressIndicator
import dev.keliver.material.compose.NavigationBar
import dev.keliver.material.compose.NavigationRail
import dev.keliver.material.compose.OutlinedButton
import dev.keliver.material.compose.OutlinedCard
import dev.keliver.material.compose.OutlinedTextField
import dev.keliver.material.compose.RadioButton
import dev.keliver.layout.compose.Row
import dev.keliver.material.compose.ScrollableColumn
import dev.keliver.material.compose.Shimmer
import dev.keliver.material.compose.Slider
import dev.keliver.material.compose.Snackbar
import dev.keliver.layout.compose.Spacer
import dev.keliver.material.compose.StyledBox
import dev.keliver.material.compose.StyledText
import dev.keliver.material.compose.SuggestionChip
import dev.keliver.material.compose.Surface
import dev.keliver.material.compose.Switch
import dev.keliver.material.compose.Tab
import dev.keliver.material.compose.TabRow
import dev.keliver.material.compose.Text
import dev.keliver.material.compose.TextButton
import dev.keliver.material.compose.TextField
import dev.keliver.material.compose.TextInput
import dev.keliver.material.compose.Theme
import dev.keliver.material.compose.Tooltip
import dev.keliver.material.compose.TopAppBar
import dev.keliver.material.compose.VerticalDivider
import dev.keliver.material.compose.VerticalPager
import dev.keliver.material.compose.alpha
import dev.keliver.material.compose.animateContentSize
import dev.keliver.material.compose.aspectRatio
import dev.keliver.material.compose.background
import dev.keliver.material.compose.blur
import dev.keliver.material.compose.border
import dev.keliver.material.compose.cornerRadius
import dev.keliver.material.compose.cornerRadiusEach
import dev.keliver.material.compose.fillMaxHeight
import dev.keliver.material.compose.fillMaxSize
import dev.keliver.material.compose.fillWidth
import dev.keliver.material.compose.gradientBackground
import dev.keliver.material.compose.offset
import dev.keliver.material.compose.padding
import dev.keliver.material.compose.paddingEach
import dev.keliver.material.compose.rotate
import dev.keliver.material.compose.scale
import dev.keliver.material.compose.shadow
import dev.keliver.material.compose.size

/** Interprets a portal WidgetNode tree as live keliver composables. */
@Composable
fun RenderNode(node: WidgetNode) {
  when (node.type) {
    "AlertDialog" -> AlertDialog(
      modifier = nodeModifier(node),
      title = node.strB("title"),
      text = node.strB("text"),
      confirmText = node.strB("confirmText", "OK"),
      dismissText = node.strB("dismissText"),
      onConfirm = node.actionOf("onConfirm")?.let { n -> { PreviewBindings.fire(n) } },
      onDismiss = node.actionOf("onDismiss")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "AnimatedBorder" -> AnimatedBorder(
      modifier = nodeModifier(node),
      cornerRadiusDp = node.intB("cornerRadiusDp", 8),
      strokeWidthDp = node.intB("strokeWidthDp", 1),
      baseColorArgb = node.intB("baseColorArgb", 0),
      cometColorArgb = node.intB("cometColorArgb", 0),
      durationMs = node.intB("durationMs", 1800),
      segmentLenDp = node.intB("segmentLenDp", 50),
      effect = node.intB("effect", 0),
      colorsArgb = node.intList("colorsArgb"),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    ) { node.children.forEach { RenderNode(it) } }
    "AnimatedVisibility" -> AnimatedVisibility(
      modifier = nodeModifier(node),
      visible = node.boolB("visible", true),
    ) { node.children.forEach { RenderNode(it) } }
    "AsyncImage" -> AsyncImage(
      modifier = nodeModifier(node),
      url = node.strB("url"),
      contentScale = node.intB("contentScale", 0),
      widthDp = node.intB("widthDp", 0),
      heightDp = node.intB("heightDp", 0),
      blurDp = node.intB("blurDp", 0),
      fillWidth = node.boolB("fillWidth", false),
      tintArgb = node.intB("tintArgb", 0),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "Badge" -> Badge(
      modifier = nodeModifier(node),
      text = node.strB("text"),
    )
    "BottomAppBar" -> BottomAppBar(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "BottomSheet" -> BottomSheet(
      modifier = nodeModifier(node),
      visible = node.boolB("visible", false),
      contentPaddingDp = node.intB("contentPaddingDp", 0),
      onDismiss = node.actionOf("onDismiss")?.let { n -> { PreviewBindings.fire(n) } },
    ) { node.children.forEach { RenderNode(it) } }
    "Box" -> Box(
      modifier = nodeModifier(node),
      width = constraintOf(node.intB("width", 0)),
      height = constraintOf(node.intB("height", 0)),
      horizontalAlignment = crossAxisOf(node.intB("horizontalAlignment", 0)),
      verticalAlignment = crossAxisOf(node.intB("verticalAlignment", 0)),
    ) { node.children.forEach { RenderNode(it) } }
    "Button" -> Button(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      enabled = node.boolB("enabled", true),
      containerArgb = node.intB("containerArgb", 0),
      contentArgb = node.intB("contentArgb", 0),
      cornerRadiusDp = node.intB("cornerRadiusDp", 0),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "Card" -> Card(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "Checkbox" -> Checkbox(
      modifier = nodeModifier(node),
      checked = node.boolB("checked", false),
      enabled = node.boolB("enabled", true),
      onCheckedChange = node.actionOf("onCheckedChange")?.let { n -> { _ -> PreviewBindings.fire(n) } },
    )
    "Chip" -> Chip(
      modifier = nodeModifier(node),
      label = node.strB("label"),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "CircularProgressIndicator" -> CircularProgressIndicator(
      modifier = nodeModifier(node),
      progress = node.dblB("progress", -1.0).toFloat(),
    )
    "Clickable" -> Clickable(
      modifier = nodeModifier(node),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    ) { node.children.forEach { RenderNode(it) } }
    "Column" -> Column(
      modifier = nodeModifier(node),
      width = constraintOf(node.intB("width", 0)),
      height = constraintOf(node.intB("height", 0)),
      overflow = overflowOf(node.intB("overflow", 0)),
      horizontalAlignment = crossAxisOf(node.intB("horizontalAlignment", 0)),
      verticalAlignment = mainAxisOf(node.intB("verticalAlignment", 0)),
      onScroll = node.actionOf("onScroll")?.let { n -> { _ -> PreviewBindings.fire(n) } },
    ) { node.children.forEach { RenderNode(it) } }
    "Dialog" -> Dialog(
      modifier = nodeModifier(node),
      onDismiss = node.actionOf("onDismiss")?.let { n -> { PreviewBindings.fire(n) } },
    ) { node.children.forEach { RenderNode(it) } }
    "Divider" -> Divider(
      modifier = nodeModifier(node),
      thickness = node.intB("thickness", 1),
    )
    "ElevatedButton" -> ElevatedButton(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      enabled = node.boolB("enabled", true),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "ElevatedCard" -> ElevatedCard(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "ExtendedFloatingActionButton" -> ExtendedFloatingActionButton(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "FilledTonalButton" -> FilledTonalButton(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      enabled = node.boolB("enabled", true),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "FilterChip" -> FilterChip(
      modifier = nodeModifier(node),
      label = node.strB("label"),
      selected = node.boolB("selected", false),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "FloatingActionButton" -> FloatingActionButton(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "FlowColumn" -> FlowColumn(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "FlowRow" -> FlowRow(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "HorizontalPager" -> HorizontalPager(
      modifier = nodeModifier(node),
      autoScrollMs = node.intB("autoScrollMs", 0),
      showIndicator = node.boolB("showIndicator", false),
      indicatorActiveArgb = node.intB("indicatorActiveArgb", 0),
      indicatorInactiveArgb = node.intB("indicatorInactiveArgb", 0),
      contentPaddingDp = node.intB("contentPaddingDp", 0),
    ) { node.children.forEach { RenderNode(it) } }
    "IconButton" -> IconButton(
      modifier = nodeModifier(node),
      imageUrl = node.strB("imageUrl"),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "Image" -> Image(
      modifier = nodeModifier(node),
      url = node.strB("url"),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "InputChip" -> InputChip(
      modifier = nodeModifier(node),
      label = node.strB("label"),
      selected = node.boolB("selected", false),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "LazyHorizontalGrid" -> LazyHorizontalGrid(
      modifier = nodeModifier(node),
      rows = node.intB("rows", 2),
    ) { node.children.forEach { RenderNode(it) } }
    "LazyVerticalGrid" -> LazyVerticalGrid(
      modifier = nodeModifier(node),
      columns = node.intB("columns", 2),
    ) { node.children.forEach { RenderNode(it) } }
    "LinearProgressIndicator" -> LinearProgressIndicator(
      modifier = nodeModifier(node),
      progress = node.dblB("progress", -1.0).toFloat(),
    )
    "NavigationBar" -> NavigationBar(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "NavigationRail" -> NavigationRail(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "OutlinedButton" -> OutlinedButton(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      enabled = node.boolB("enabled", true),
      iconUrl = node.strB("iconUrl"),
      iconSizeDp = node.intB("iconSizeDp", 18),
      containerArgb = node.intB("containerArgb", 0),
      contentArgb = node.intB("contentArgb", 0),
      borderArgb = node.intB("borderArgb", 0),
      cornerRadiusDp = node.intB("cornerRadiusDp", 0),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "OutlinedCard" -> OutlinedCard(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "OutlinedTextField" -> OutlinedTextField(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      placeholder = node.strB("placeholder"),
      label = node.strB("label"),
      leadingText = node.strB("leadingText"),
      keyboardType = node.intB("keyboardType", 0),
      singleLine = node.boolB("singleLine", true),
      maxLines = node.intB("maxLines", 1),
      isError = node.boolB("isError", false),
      supportingText = node.strB("supportingText"),
      borderArgb = node.intB("borderArgb", 0),
      cornerRadiusDp = node.intB("cornerRadiusDp", 0),
      onValueChange = node.actionOf("onValueChange")?.let { n -> { _ -> PreviewBindings.fire(n) } },
    )
    "RadioButton" -> RadioButton(
      modifier = nodeModifier(node),
      selected = node.boolB("selected", false),
      enabled = node.boolB("enabled", true),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "Row" -> Row(
      modifier = nodeModifier(node),
      width = constraintOf(node.intB("width", 0)),
      height = constraintOf(node.intB("height", 0)),
      overflow = overflowOf(node.intB("overflow", 0)),
      horizontalAlignment = mainAxisOf(node.intB("horizontalAlignment", 0)),
      verticalAlignment = crossAxisOf(node.intB("verticalAlignment", 0)),
      onScroll = node.actionOf("onScroll")?.let { n -> { _ -> PreviewBindings.fire(n) } },
    ) { node.children.forEach { RenderNode(it) } }
    "ScrollableColumn" -> ScrollableColumn(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "Shimmer" -> Shimmer(
      modifier = nodeModifier(node),
      widthDp = node.intB("widthDp", 0),
      heightDp = node.intB("heightDp", 16),
      cornerRadiusDp = node.intB("cornerRadiusDp", 8),
    )
    "Slider" -> Slider(
      modifier = nodeModifier(node),
      position = node.dblB("position", 0.0).toFloat(),
      enabled = node.boolB("enabled", true),
      onValueChange = node.actionOf("onValueChange")?.let { n -> { _ -> PreviewBindings.fire(n) } },
    )
    "Snackbar" -> Snackbar(
      modifier = nodeModifier(node),
      message = node.strB("message"),
    )
    "Spacer" -> Spacer(
      modifier = nodeModifier(node),
      width = Dp(node.dblB("width", 0.0)),
      height = Dp(node.dblB("height", 0.0)),
    )
    "StyledBox" -> StyledBox(
      modifier = nodeModifier(node),
      colorArgb = node.intB("colorArgb", 0),
      gradientStartArgb = node.intB("gradientStartArgb", 0),
      gradientEndArgb = node.intB("gradientEndArgb", 0),
      cornerRadiusDp = node.intB("cornerRadiusDp", 0),
      widthDp = node.intB("widthDp", 0),
      heightDp = node.intB("heightDp", 0),
      paddingDp = node.intB("paddingDp", 0),
      fillWidth = node.boolB("fillWidth", false),
      contentAlignment = node.intB("contentAlignment", 0),
      offsetYDp = node.intB("offsetYDp", 0),
      elevationDp = node.intB("elevationDp", 0),
      borderColorArgb = node.intB("borderColorArgb", 0),
      borderWidthDp = node.intB("borderWidthDp", 0),
      gradientVertical = node.boolB("gradientVertical", false),
      gradientColorsArgb = node.intList("gradientColorsArgb"),
      gradientStops = node.floatList("gradientStops"),
      gradientDirection = node.intB("gradientDirection", 0),
      cornerTopStartDp = node.intB("cornerTopStartDp", -1),
      cornerTopEndDp = node.intB("cornerTopEndDp", -1),
      cornerBottomStartDp = node.intB("cornerBottomStartDp", -1),
      cornerBottomEndDp = node.intB("cornerBottomEndDp", -1),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    ) { node.children.forEach { RenderNode(it) } }
    "StyledText" -> StyledText(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      fontSize = node.intB("fontSize", 14),
      bold = node.boolB("bold", false),
      colorArgb = node.intB("colorArgb", 0),
      align = node.intB("align", 0),
      maxLines = node.intB("maxLines", 0),
      overflow = node.intB("overflow", 0),
      lineHeightSp = node.intB("lineHeightSp", 0),
      letterSpacingX100 = node.intB("letterSpacingX100", 0),
      italic = node.boolB("italic", false),
      underline = node.boolB("underline", false),
      strikethrough = node.boolB("strikethrough", false),
      weight = node.intB("weight", 0),
      colorRole = node.intB("colorRole", 0),
    )
    "SuggestionChip" -> SuggestionChip(
      modifier = nodeModifier(node),
      label = node.strB("label"),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "Surface" -> Surface(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    "Switch" -> Switch(
      modifier = nodeModifier(node),
      checked = node.boolB("checked", false),
      enabled = node.boolB("enabled", true),
      onCheckedChange = node.actionOf("onCheckedChange")?.let { n -> { _ -> PreviewBindings.fire(n) } },
    )
    "Tab" -> Tab(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      selected = node.boolB("selected", false),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "TabRow" -> TabRow(
      modifier = nodeModifier(node),
      selectedIndex = node.intB("selectedIndex", 0),
    ) { node.children.forEach { RenderNode(it) } }
    "Text" -> Text(
      modifier = nodeModifier(node),
      text = node.strB("text"),
    )
    "TextButton" -> TextButton(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      enabled = node.boolB("enabled", true),
      onClick = node.actionOf("onClick")?.let { n -> { PreviewBindings.fire(n) } },
    )
    "TextField" -> TextField(
      modifier = nodeModifier(node),
      text = node.strB("text"),
      placeholder = node.strB("placeholder"),
      onValueChange = node.actionOf("onValueChange")?.let { n -> { _ -> PreviewBindings.fire(n) } },
    )
    "TextInput" -> TextInput(
      modifier = nodeModifier(node),
      hint = node.strB("hint"),
      onChange = node.actionOf("onChange")?.let { n -> { _ -> PreviewBindings.fire(n) } },
    )
    "Theme" -> Theme(
      modifier = nodeModifier(node),
      dark = node.boolB("dark", false),
      primaryArgb = node.intB("primaryArgb", 0),
      onPrimaryArgb = node.intB("onPrimaryArgb", 0),
      secondaryArgb = node.intB("secondaryArgb", 0),
      onSecondaryArgb = node.intB("onSecondaryArgb", 0),
      surfaceArgb = node.intB("surfaceArgb", 0),
      onSurfaceArgb = node.intB("onSurfaceArgb", 0),
      surfaceVariantArgb = node.intB("surfaceVariantArgb", 0),
      onSurfaceVariantArgb = node.intB("onSurfaceVariantArgb", 0),
      backgroundArgb = node.intB("backgroundArgb", 0),
      onBackgroundArgb = node.intB("onBackgroundArgb", 0),
      errorArgb = node.intB("errorArgb", 0),
      outlineArgb = node.intB("outlineArgb", 0),
    ) { node.children.forEach { RenderNode(it) } }
    "Tooltip" -> Tooltip(
      modifier = nodeModifier(node),
      text = node.strB("text"),
    ) { node.children.forEach { RenderNode(it) } }
    "TopAppBar" -> TopAppBar(
      modifier = nodeModifier(node),
      title = node.strB("title"),
    )
    "VerticalDivider" -> VerticalDivider(
      modifier = nodeModifier(node),
      thickness = node.intB("thickness", 1),
    )
    "VerticalPager" -> VerticalPager(
      modifier = nodeModifier(node),
    ) { node.children.forEach { RenderNode(it) } }
    else -> StyledText(text = "\u26a0 unknown widget: ${node.type}", colorArgb = -5238254)
  }
}

/** Builds the Modifier chain from a node's namespaced "mod.*" props. */
private fun nodeModifier(node: WidgetNode): Modifier {
  var m: Modifier = Modifier
  if ("mod.Alpha.pct" in node.props) m = m.alpha(node.intB("mod.Alpha.pct", 0))
  if (node.bool("mod.AnimateContentSize")) m = m.animateContentSize()
  if ("mod.AspectRatio.ratio" in node.props) m = m.aspectRatio(node.dblB("mod.AspectRatio.ratio", 0.0).toFloat())
  if ("mod.Background.colorArgb" in node.props) m = m.background(node.intB("mod.Background.colorArgb", 0))
  if ("mod.Blur.radiusDp" in node.props) m = m.blur(node.intB("mod.Blur.radiusDp", 0))
  if ("mod.Border.widthDp" in node.props || "mod.Border.colorArgb" in node.props) m = m.border(node.intB("mod.Border.widthDp", 0), node.intB("mod.Border.colorArgb", 0))
  if ("mod.CornerRadius.radiusDp" in node.props) m = m.cornerRadius(node.intB("mod.CornerRadius.radiusDp", 0))
  if ("mod.CornerRadiusEach.topStartDp" in node.props || "mod.CornerRadiusEach.topEndDp" in node.props || "mod.CornerRadiusEach.bottomEndDp" in node.props || "mod.CornerRadiusEach.bottomStartDp" in node.props) m = m.cornerRadiusEach(node.intB("mod.CornerRadiusEach.topStartDp", 0), node.intB("mod.CornerRadiusEach.topEndDp", 0), node.intB("mod.CornerRadiusEach.bottomEndDp", 0), node.intB("mod.CornerRadiusEach.bottomStartDp", 0))
  if (node.bool("mod.FillMaxHeight")) m = m.fillMaxHeight()
  if (node.bool("mod.FillMaxSize")) m = m.fillMaxSize()
  if (node.bool("mod.FillWidth")) m = m.fillWidth()
  if ("mod.GradientBackground.startArgb" in node.props || "mod.GradientBackground.endArgb" in node.props) m = m.gradientBackground(node.intB("mod.GradientBackground.startArgb", 0), node.intB("mod.GradientBackground.endArgb", 0))
  if ("mod.Offset.xDp" in node.props || "mod.Offset.yDp" in node.props) m = m.offset(node.intB("mod.Offset.xDp", 0), node.intB("mod.Offset.yDp", 0))
  if ("mod.Padding.allDp" in node.props) m = m.padding(node.intB("mod.Padding.allDp", 0))
  if ("mod.PaddingEach.startDp" in node.props || "mod.PaddingEach.topDp" in node.props || "mod.PaddingEach.endDp" in node.props || "mod.PaddingEach.bottomDp" in node.props) m = m.paddingEach(node.intB("mod.PaddingEach.startDp", 0), node.intB("mod.PaddingEach.topDp", 0), node.intB("mod.PaddingEach.endDp", 0), node.intB("mod.PaddingEach.bottomDp", 0))
  if ("mod.Rotate.degrees" in node.props) m = m.rotate(node.intB("mod.Rotate.degrees", 0))
  if ("mod.Scale.percent" in node.props) m = m.scale(node.intB("mod.Scale.percent", 0))
  if ("mod.Shadow.elevationDp" in node.props) m = m.shadow(node.intB("mod.Shadow.elevationDp", 0))
  if ("mod.Size.widthDp" in node.props || "mod.Size.heightDp" in node.props) m = m.size(node.intB("mod.Size.widthDp", 0), node.intB("mod.Size.heightDp", 0))
  return m
}
