// GENERATED by :portal-schema-codegen — do not edit. Run ./gradlew :portal-schema-codegen:generatePortalCode
package dev.keliver.portal.render

import androidx.compose.runtime.Composable
import dev.keliver.portal.WidgetNode
import dev.keliver.portal.bool
import dev.keliver.portal.dbl
import dev.keliver.portal.floatList
import dev.keliver.portal.int
import dev.keliver.portal.intList
import dev.keliver.portal.str
import dev.keliver.ui.Dp
import dev.keliver.material.compose.AlertDialog
import dev.keliver.material.compose.AnimatedBorder
import dev.keliver.material.compose.AnimatedVisibility
import dev.keliver.material.compose.AsyncImage
import dev.keliver.material.compose.Badge
import dev.keliver.material.compose.BottomAppBar
import dev.keliver.material.compose.BottomSheet
import dev.keliver.layout.compose.Box
import dev.keliver.material.compose.Button
import dev.keliver.material.compose.Card
import dev.keliver.material.compose.Checkbox
import dev.keliver.material.compose.Chip
import dev.keliver.material.compose.CircularProgressIndicator
import dev.keliver.material.compose.Clickable
import dev.keliver.layout.compose.Column
import dev.keliver.material.compose.Dialog
import dev.keliver.material.compose.Divider
import dev.keliver.material.compose.ElevatedButton
import dev.keliver.material.compose.ElevatedCard
import dev.keliver.material.compose.ExtendedFloatingActionButton
import dev.keliver.material.compose.FilledTonalButton
import dev.keliver.material.compose.FilterChip
import dev.keliver.material.compose.FloatingActionButton
import dev.keliver.material.compose.FlowColumn
import dev.keliver.material.compose.FlowRow
import dev.keliver.material.compose.HorizontalPager
import dev.keliver.material.compose.IconButton
import dev.keliver.material.compose.Image
import dev.keliver.material.compose.InputChip
import dev.keliver.material.compose.LazyHorizontalGrid
import dev.keliver.material.compose.LazyVerticalGrid
import dev.keliver.material.compose.LinearProgressIndicator
import dev.keliver.material.compose.NavigationBar
import dev.keliver.material.compose.NavigationRail
import dev.keliver.material.compose.OutlinedButton
import dev.keliver.material.compose.OutlinedCard
import dev.keliver.material.compose.OutlinedTextField
import dev.keliver.material.compose.RadioButton
import dev.keliver.layout.compose.Row
import dev.keliver.material.compose.ScrollableColumn
import dev.keliver.material.compose.Shimmer
import dev.keliver.material.compose.Slider
import dev.keliver.material.compose.Snackbar
import dev.keliver.layout.compose.Spacer
import dev.keliver.material.compose.StyledBox
import dev.keliver.material.compose.StyledText
import dev.keliver.material.compose.SuggestionChip
import dev.keliver.material.compose.Surface
import dev.keliver.material.compose.Switch
import dev.keliver.material.compose.Tab
import dev.keliver.material.compose.TabRow
import dev.keliver.material.compose.Text
import dev.keliver.material.compose.TextButton
import dev.keliver.material.compose.TextField
import dev.keliver.material.compose.TextInput
import dev.keliver.material.compose.Theme
import dev.keliver.material.compose.Tooltip
import dev.keliver.material.compose.TopAppBar
import dev.keliver.material.compose.VerticalDivider
import dev.keliver.material.compose.VerticalPager

/** Interprets a portal WidgetNode tree as live keliver composables. */
@Composable
fun RenderNode(node: WidgetNode) {
  when (node.type) {
    "AlertDialog" -> AlertDialog(
      title = node.str("title"),
      text = node.str("text"),
      confirmText = node.str("confirmText", "OK"),
      dismissText = node.str("dismissText"),
    )
    "AnimatedBorder" -> AnimatedBorder(
      cornerRadiusDp = node.int("cornerRadiusDp", 8),
      strokeWidthDp = node.int("strokeWidthDp", 1),
      baseColorArgb = node.int("baseColorArgb", 0),
      cometColorArgb = node.int("cometColorArgb", 0),
      durationMs = node.int("durationMs", 1800),
      segmentLenDp = node.int("segmentLenDp", 50),
      effect = node.int("effect", 0),
      colorsArgb = node.intList("colorsArgb"),
    ) { node.children.forEach { RenderNode(it) } }
    "AnimatedVisibility" -> AnimatedVisibility(
      visible = node.bool("visible", true),
    ) { node.children.forEach { RenderNode(it) } }
    "AsyncImage" -> AsyncImage(
      url = node.str("url"),
      contentScale = node.int("contentScale", 0),
      widthDp = node.int("widthDp", 0),
      heightDp = node.int("heightDp", 0),
      blurDp = node.int("blurDp", 0),
      fillWidth = node.bool("fillWidth", false),
      tintArgb = node.int("tintArgb", 0),
    )
    "Badge" -> Badge(
      text = node.str("text"),
    )
    "BottomAppBar" -> BottomAppBar() { node.children.forEach { RenderNode(it) } }
    "BottomSheet" -> BottomSheet(
      visible = node.bool("visible", false),
      contentPaddingDp = node.int("contentPaddingDp", 0),
    ) { node.children.forEach { RenderNode(it) } }
    "Box" -> Box(
      width = constraintOf(node.int("width", 0)),
      height = constraintOf(node.int("height", 0)),
      horizontalAlignment = crossAxisOf(node.int("horizontalAlignment", 0)),
      verticalAlignment = crossAxisOf(node.int("verticalAlignment", 0)),
    ) { node.children.forEach { RenderNode(it) } }
    "Button" -> Button(
      text = node.str("text"),
      enabled = node.bool("enabled", true),
      containerArgb = node.int("containerArgb", 0),
      contentArgb = node.int("contentArgb", 0),
      cornerRadiusDp = node.int("cornerRadiusDp", 0),
    )
    "Card" -> Card() { node.children.forEach { RenderNode(it) } }
    "Checkbox" -> Checkbox(
      checked = node.bool("checked", false),
      enabled = node.bool("enabled", true),
    )
    "Chip" -> Chip(
      label = node.str("label"),
    )
    "CircularProgressIndicator" -> CircularProgressIndicator(
      progress = node.dbl("progress", -1.0).toFloat(),
    )
    "Clickable" -> Clickable() { node.children.forEach { RenderNode(it) } }
    "Column" -> Column(
      width = constraintOf(node.int("width", 0)),
      height = constraintOf(node.int("height", 0)),
      overflow = overflowOf(node.int("overflow", 0)),
      horizontalAlignment = crossAxisOf(node.int("horizontalAlignment", 0)),
      verticalAlignment = mainAxisOf(node.int("verticalAlignment", 0)),
    ) { node.children.forEach { RenderNode(it) } }
    "Dialog" -> Dialog() { node.children.forEach { RenderNode(it) } }
    "Divider" -> Divider(
      thickness = node.int("thickness", 1),
    )
    "ElevatedButton" -> ElevatedButton(
      text = node.str("text"),
      enabled = node.bool("enabled", true),
    )
    "ElevatedCard" -> ElevatedCard() { node.children.forEach { RenderNode(it) } }
    "ExtendedFloatingActionButton" -> ExtendedFloatingActionButton(
      text = node.str("text"),
    )
    "FilledTonalButton" -> FilledTonalButton(
      text = node.str("text"),
      enabled = node.bool("enabled", true),
    )
    "FilterChip" -> FilterChip(
      label = node.str("label"),
      selected = node.bool("selected", false),
    )
    "FloatingActionButton" -> FloatingActionButton(
      text = node.str("text"),
    )
    "FlowColumn" -> FlowColumn() { node.children.forEach { RenderNode(it) } }
    "FlowRow" -> FlowRow() { node.children.forEach { RenderNode(it) } }
    "HorizontalPager" -> HorizontalPager(
      autoScrollMs = node.int("autoScrollMs", 0),
      showIndicator = node.bool("showIndicator", false),
      indicatorActiveArgb = node.int("indicatorActiveArgb", 0),
      indicatorInactiveArgb = node.int("indicatorInactiveArgb", 0),
      contentPaddingDp = node.int("contentPaddingDp", 0),
    ) { node.children.forEach { RenderNode(it) } }
    "IconButton" -> IconButton(
      imageUrl = node.str("imageUrl"),
    )
    "Image" -> Image(
      url = node.str("url"),
    )
    "InputChip" -> InputChip(
      label = node.str("label"),
      selected = node.bool("selected", false),
    )
    "LazyHorizontalGrid" -> LazyHorizontalGrid(
      rows = node.int("rows", 2),
    ) { node.children.forEach { RenderNode(it) } }
    "LazyVerticalGrid" -> LazyVerticalGrid(
      columns = node.int("columns", 2),
    ) { node.children.forEach { RenderNode(it) } }
    "LinearProgressIndicator" -> LinearProgressIndicator(
      progress = node.dbl("progress", -1.0).toFloat(),
    )
    "NavigationBar" -> NavigationBar() { node.children.forEach { RenderNode(it) } }
    "NavigationRail" -> NavigationRail() { node.children.forEach { RenderNode(it) } }
    "OutlinedButton" -> OutlinedButton(
      text = node.str("text"),
      enabled = node.bool("enabled", true),
      iconUrl = node.str("iconUrl"),
      iconSizeDp = node.int("iconSizeDp", 18),
      containerArgb = node.int("containerArgb", 0),
      contentArgb = node.int("contentArgb", 0),
      borderArgb = node.int("borderArgb", 0),
      cornerRadiusDp = node.int("cornerRadiusDp", 0),
    )
    "OutlinedCard" -> OutlinedCard() { node.children.forEach { RenderNode(it) } }
    "OutlinedTextField" -> OutlinedTextField(
      text = node.str("text"),
      placeholder = node.str("placeholder"),
      label = node.str("label"),
      leadingText = node.str("leadingText"),
      keyboardType = node.int("keyboardType", 0),
      singleLine = node.bool("singleLine", true),
      maxLines = node.int("maxLines", 1),
      isError = node.bool("isError", false),
      supportingText = node.str("supportingText"),
      borderArgb = node.int("borderArgb", 0),
      cornerRadiusDp = node.int("cornerRadiusDp", 0),
    )
    "RadioButton" -> RadioButton(
      selected = node.bool("selected", false),
      enabled = node.bool("enabled", true),
    )
    "Row" -> Row(
      width = constraintOf(node.int("width", 0)),
      height = constraintOf(node.int("height", 0)),
      overflow = overflowOf(node.int("overflow", 0)),
      horizontalAlignment = mainAxisOf(node.int("horizontalAlignment", 0)),
      verticalAlignment = crossAxisOf(node.int("verticalAlignment", 0)),
    ) { node.children.forEach { RenderNode(it) } }
    "ScrollableColumn" -> ScrollableColumn() { node.children.forEach { RenderNode(it) } }
    "Shimmer" -> Shimmer(
      widthDp = node.int("widthDp", 0),
      heightDp = node.int("heightDp", 16),
      cornerRadiusDp = node.int("cornerRadiusDp", 8),
    )
    "Slider" -> Slider(
      position = node.dbl("position", 0.0).toFloat(),
      enabled = node.bool("enabled", true),
    )
    "Snackbar" -> Snackbar(
      message = node.str("message"),
    )
    "Spacer" -> Spacer(
      width = Dp(node.dbl("width", 0.0)),
      height = Dp(node.dbl("height", 0.0)),
    )
    "StyledBox" -> StyledBox(
      colorArgb = node.int("colorArgb", 0),
      gradientStartArgb = node.int("gradientStartArgb", 0),
      gradientEndArgb = node.int("gradientEndArgb", 0),
      cornerRadiusDp = node.int("cornerRadiusDp", 0),
      widthDp = node.int("widthDp", 0),
      heightDp = node.int("heightDp", 0),
      paddingDp = node.int("paddingDp", 0),
      fillWidth = node.bool("fillWidth", false),
      contentAlignment = node.int("contentAlignment", 0),
      offsetYDp = node.int("offsetYDp", 0),
      elevationDp = node.int("elevationDp", 0),
      borderColorArgb = node.int("borderColorArgb", 0),
      borderWidthDp = node.int("borderWidthDp", 0),
      gradientVertical = node.bool("gradientVertical", false),
      gradientColorsArgb = node.intList("gradientColorsArgb"),
      gradientStops = node.floatList("gradientStops"),
      gradientDirection = node.int("gradientDirection", 0),
      cornerTopStartDp = node.int("cornerTopStartDp", -1),
      cornerTopEndDp = node.int("cornerTopEndDp", -1),
      cornerBottomStartDp = node.int("cornerBottomStartDp", -1),
      cornerBottomEndDp = node.int("cornerBottomEndDp", -1),
    ) { node.children.forEach { RenderNode(it) } }
    "StyledText" -> StyledText(
      text = node.str("text"),
      fontSize = node.int("fontSize", 14),
      bold = node.bool("bold", false),
      colorArgb = node.int("colorArgb", 0),
      align = node.int("align", 0),
      maxLines = node.int("maxLines", 0),
      overflow = node.int("overflow", 0),
      lineHeightSp = node.int("lineHeightSp", 0),
      letterSpacingX100 = node.int("letterSpacingX100", 0),
      italic = node.bool("italic", false),
      underline = node.bool("underline", false),
      strikethrough = node.bool("strikethrough", false),
      weight = node.int("weight", 0),
      colorRole = node.int("colorRole", 0),
    )
    "SuggestionChip" -> SuggestionChip(
      label = node.str("label"),
    )
    "Surface" -> Surface() { node.children.forEach { RenderNode(it) } }
    "Switch" -> Switch(
      checked = node.bool("checked", false),
      enabled = node.bool("enabled", true),
    )
    "Tab" -> Tab(
      text = node.str("text"),
      selected = node.bool("selected", false),
    )
    "TabRow" -> TabRow(
      selectedIndex = node.int("selectedIndex", 0),
    ) { node.children.forEach { RenderNode(it) } }
    "Text" -> Text(
      text = node.str("text"),
    )
    "TextButton" -> TextButton(
      text = node.str("text"),
      enabled = node.bool("enabled", true),
    )
    "TextField" -> TextField(
      text = node.str("text"),
      placeholder = node.str("placeholder"),
    )
    "TextInput" -> TextInput(
      hint = node.str("hint"),
    )
    "Theme" -> Theme(
      dark = node.bool("dark", false),
      primaryArgb = node.int("primaryArgb", 0),
      onPrimaryArgb = node.int("onPrimaryArgb", 0),
      secondaryArgb = node.int("secondaryArgb", 0),
      onSecondaryArgb = node.int("onSecondaryArgb", 0),
      surfaceArgb = node.int("surfaceArgb", 0),
      onSurfaceArgb = node.int("onSurfaceArgb", 0),
      surfaceVariantArgb = node.int("surfaceVariantArgb", 0),
      onSurfaceVariantArgb = node.int("onSurfaceVariantArgb", 0),
      backgroundArgb = node.int("backgroundArgb", 0),
      onBackgroundArgb = node.int("onBackgroundArgb", 0),
      errorArgb = node.int("errorArgb", 0),
      outlineArgb = node.int("outlineArgb", 0),
    ) { node.children.forEach { RenderNode(it) } }
    "Tooltip" -> Tooltip(
      text = node.str("text"),
    ) { node.children.forEach { RenderNode(it) } }
    "TopAppBar" -> TopAppBar(
      title = node.str("title"),
    )
    "VerticalDivider" -> VerticalDivider(
      thickness = node.int("thickness", 1),
    )
    "VerticalPager" -> VerticalPager() { node.children.forEach { RenderNode(it) } }
    else -> StyledText(text = "\u26a0 unknown widget: ${node.type}", colorArgb = -5238254)
  }
}
