package dev.keliver.portal.codegen

private fun literalExpr(p: MappedProp): String {
  val v = "node.props[\"${p.name}\"]"
  return when (p.kind) {
    MappedKind.TEXT -> "fmtString($v ?: \"\")"
    MappedKind.INT -> "fmtInt($v)"
    MappedKind.BOOL -> "fmtBool($v)"
    MappedKind.DOUBLE -> "fmtDouble($v)"
    MappedKind.FLOAT -> "fmtFloat($v)"
    MappedKind.INT_LIST -> "fmtIntList($v)"
    MappedKind.FLOAT_LIST -> "fmtFloatList($v)"
    MappedKind.DP -> "fmtDp($v)"
    MappedKind.CONSTRAINT -> "fmtConstraint($v)"
    MappedKind.CROSS_AXIS -> "fmtCrossAxis($v)"
    MappedKind.MAIN_AXIS -> "fmtMainAxis($v)"
    MappedKind.OVERFLOW -> "fmtOverflow($v)"
  }
}

/** Support imports the EXPORTED code needs when a widget with these kinds is used. */
private fun supportImports(w: WidgetPlan.Include): List<String> = buildList {
  if (w.props.any { it.kind == MappedKind.DP }) add("dev.keliver.ui.Dp")
  if (w.props.any { it.kind == MappedKind.CONSTRAINT }) add("dev.keliver.layout.api.Constraint")
  if (w.props.any { it.kind == MappedKind.CROSS_AXIS }) add("dev.keliver.layout.api.CrossAxisAlignment")
  if (w.props.any { it.kind == MappedKind.MAIN_AXIS }) add("dev.keliver.layout.api.MainAxisAlignment")
  if (w.props.any { it.kind == MappedKind.OVERFLOW }) add("dev.keliver.layout.api.Overflow")
}

fun emitExporter(widgets: List<WidgetPlan.Include>): String = buildString {
  val sorted = widgets.sortedBy { it.name }
  appendLine("// GENERATED by :portal-schema-codegen — do not edit. Run ./gradlew :portal-schema-codegen:generatePortalCode")
  appendLine("package dev.keliver.portal")
  appendLine()
  appendLine("private val composableImport: Map<String, String> = mapOf(")
  for (w in sorted) appendLine("  \"${w.name}\" to \"${w.composePackage}.${w.name}\",")
  appendLine(")")
  appendLine()
  appendLine("private val supportImports: Map<String, List<String>> = mapOf(")
  for (w in sorted) {
    val sup = supportImports(w)
    if (sup.isNotEmpty()) appendLine("  \"${w.name}\" to listOf(${sup.joinToString(", ") { "\"$it\"" }}),")
  }
  appendLine(")")
  appendLine()
  appendLine(
    """
    |private fun collectTypes(node: WidgetNode, out: MutableSet<String>) {
    |  out += node.type
    |  node.children.forEach { collectTypes(it, out) }
    |}
    |
    |private fun fmtString(v: Any?): String = "\"" + v.toString().replace("\\", "\\\\").replace("\"", "\\\"") + "\""
    |private fun fmtInt(v: Any?): String = ((v as? Int) ?: 0).toString()
    |private fun fmtBool(v: Any?): String = ((v as? Boolean) ?: false).toString()
    |private fun fmtDouble(v: Any?): String = ((v as? Double) ?: (v as? Int)?.toDouble() ?: 0.0).toString()
    |private fun fmtFloat(v: Any?): String = "${'$'}{fmtDouble(v)}f"
    |private fun fmtDp(v: Any?): String = "Dp(${'$'}{fmtDouble(v)})"
    |private fun fmtIntList(v: Any?): String = "listOf(" + ((v as? List<*>)?.joinToString(", ") ?: "") + ")"
    |private fun fmtFloatList(v: Any?): String = "listOf(" + ((v as? List<*>)?.joinToString(", ") { "${'$'}{it}f" } ?: "") + ")"
    |private fun fmtConstraint(v: Any?): String = if (((v as? Int) ?: 0) == 1) "Constraint.Fill" else "Constraint.Wrap"
    |private fun fmtCrossAxis(v: Any?): String = when ((v as? Int) ?: 0) {
    |  1 -> "CrossAxisAlignment.Center"
    |  2 -> "CrossAxisAlignment.End"
    |  3 -> "CrossAxisAlignment.Stretch"
    |  else -> "CrossAxisAlignment.Start"
    |}
    |private fun fmtOverflow(v: Any?): String = if (((v as? Int) ?: 0) == 1) "Overflow.Scroll" else "Overflow.Clip"
    |private fun fmtMainAxis(v: Any?): String = when ((v as? Int) ?: 0) {
    |  1 -> "MainAxisAlignment.Center"
    |  2 -> "MainAxisAlignment.End"
    |  3 -> "MainAxisAlignment.SpaceBetween"
    |  4 -> "MainAxisAlignment.SpaceAround"
    |  5 -> "MainAxisAlignment.SpaceEvenly"
    |  else -> "MainAxisAlignment.Start"
    |}
    """.trimMargin(),
  )
  appendLine()
  appendLine("fun exportKotlin(tree: WidgetNode, functionName: String = \"ExportedScreen\"): String {")
  appendLine("  val used = mutableSetOf<String>()")
  appendLine("  collectTypes(tree, used)")
  appendLine("  val sb = StringBuilder()")
  appendLine("  sb.append(\"import androidx.compose.runtime.Composable\\n\")")
  appendLine("  val imports = (used.mapNotNull { composableImport[it] } + used.flatMap { supportImports[it] ?: emptyList() }).toSortedSet()")
  appendLine("  imports.forEach { sb.append(\"import \$it\\n\") }")
  appendLine("  sb.append(\"\\n@Composable\\nfun \$functionName() {\\n\")")
  appendLine("  emitNode(sb, tree, \"  \")")
  appendLine("  sb.append(\"}\\n\")")
  appendLine("  return sb.toString()")
  appendLine("}")
  appendLine()
  appendLine("private fun emitNode(sb: StringBuilder, node: WidgetNode, indent: String) {")
  appendLine("  when (node.type) {")
  for (w in sorted) {
    appendLine("    \"${w.name}\" -> {")
    appendLine("      sb.append(\"\${indent}${w.name}(\\n\")")
    for (p in w.props) {
      if (p.required) {
        appendLine("      sb.append(\"\${indent}  ${p.name} = \${${literalExpr(p)}},\\n\")")
      } else {
        appendLine("      if (\"${p.name}\" in node.props) sb.append(\"\${indent}  ${p.name} = \${${literalExpr(p)}},\\n\")")
      }
    }
    if (w.hasChildren) {
      appendLine("      sb.append(\"\$indent) {\\n\")")
      appendLine("      node.children.forEach { emitNode(sb, it, \"\$indent  \") }")
      appendLine("      sb.append(\"\$indent}\\n\")")
    } else {
      appendLine("      sb.append(\"\$indent)\\n\")")
    }
    appendLine("    }")
  }
  appendLine("    else -> sb.append(\"\$indent// unknown widget: \${node.type}\\n\")")
  appendLine("  }")
  appendLine("}")
}
