package dev.keliver.portal.codegen

internal fun catalogKind(p: MappedProp): String = when {
  p.isColor -> "Color"
  else -> when (p.kind) {
    MappedKind.TEXT -> "Text"
    MappedKind.INT, MappedKind.CONSTRAINT, MappedKind.CROSS_AXIS, MappedKind.MAIN_AXIS, MappedKind.OVERFLOW -> "Int"
    MappedKind.BOOL -> "Bool"
    MappedKind.DOUBLE, MappedKind.FLOAT, MappedKind.DP -> "Double"
    MappedKind.INT_LIST -> "IntList"
    MappedKind.FLOAT_LIST -> "FloatList"
    MappedKind.STRING_LIST -> "StringList"
  }
}

/** camelCase → "Camel case" */
internal fun humanize(name: String): String {
  val words = name.replace(Regex("([a-z0-9])([A-Z])"), "$1 $2").lowercase()
  return words.replaceFirstChar { it.uppercase() }
}

private fun sampleValue(widgetName: String, p: MappedProp): String? = when {
  !p.required -> null
  else -> when (p.kind) {
    MappedKind.TEXT -> "\"New $widgetName\""
    MappedKind.INT, MappedKind.CONSTRAINT, MappedKind.CROSS_AXIS, MappedKind.MAIN_AXIS, MappedKind.OVERFLOW -> "0"
    MappedKind.BOOL -> "false"
    MappedKind.DOUBLE, MappedKind.FLOAT, MappedKind.DP -> "0.0"
    MappedKind.INT_LIST -> "listOf<Int>()"
    MappedKind.FLOAT_LIST -> "listOf<Float>()"
    MappedKind.STRING_LIST -> "listOf(\"Option A\", \"Option B\")"
  }
}

fun emitCatalog(widgets: List<WidgetPlan.Include>, modifiers: List<ModPlan> = emptyList()): String = buildString {
  appendLine("// GENERATED by :portal-schema-codegen — do not edit. Run ./gradlew :portal-schema-codegen:generatePortalCode")
  appendLine("package dev.keliver.portal")
  appendLine()
  appendLine("val widgetSpecs: List<WidgetSpec> = listOf(")
  for (w in widgets.sortedBy { it.name }) {
    append("  WidgetSpec(\"${w.name}\", \"${w.category}\", listOf(")
    if (w.props.isNotEmpty()) {
      appendLine()
      for (p in w.props) {
        appendLine("    PropSpec(\"${p.name}\", PropKind.${catalogKind(p)}, \"${humanize(p.name)}\"),")
      }
      append("  )")
    } else {
      append(")")
    }
    append(", acceptsChildren = ${w.hasChildren}, sampleProps = ")
    val samples = w.props.mapNotNull { p -> sampleValue(w.name, p)?.let { "\"${p.name}\" to $it" } }
    if (samples.isEmpty()) append("emptyMap()") else append("mapOf(${samples.joinToString(", ")})")
    if (w.events.isNotEmpty()) append(", events = listOf(${w.events.joinToString(", ") { "\"${it.name}\"" }})")
    appendLine("),")
  }
  // M5: logic nodes (not schema widgets) — portal-editable control flow.
  appendLine("""  WidgetSpec("Condition", "Logic", listOf(PropSpec("field", PropKind.Text, "If field (Boolean)")), acceptsChildren = true, sampleProps = mapOf("field" to "showThis")),""")
  appendLine("""  WidgetSpec("Repeat", "Logic", listOf(PropSpec("items", PropKind.Text, "Items field (List)"), PropSpec("item", PropKind.Text, "Item name")), acceptsChildren = true, sampleProps = mapOf("items" to "items", "item" to "item")),""")
  appendLine(")")
  appendLine()
  appendLine("val modifierSpecs: List<ModifierSpec> = listOf(")
  for (m in modifiers.sortedBy { it.name }) {
    append("  ModifierSpec(\"${m.name}\", listOf(")
    append(m.props.joinToString(", ") { p -> "PropSpec(\"${p.name}\", PropKind.${catalogKind(p)}, \"${humanize(p.name)}\")" })
    appendLine(")),")
  }
  appendLine(")")
  appendLine()
  appendLine("private val specsByType = widgetSpecs.associateBy { it.type }")
  appendLine()
  appendLine("fun widgetSpec(type: String): WidgetSpec? = specsByType[type]")
  appendLine()
  appendLine("fun editableProps(type: String): List<PropSpec> = specsByType[type]?.props ?: emptyList()")
}
