package dev.keliver.portal.codegen

internal fun getterExpr(p: MappedProp): String = when (p.kind) {
  MappedKind.TEXT -> {
    val d = defaultString(p.defaultExpr).replace("\\", "\\\\").replace("\"", "\\\"")
    if (d.isEmpty()) "node.str(\"${p.name}\")" else "node.str(\"${p.name}\", \"$d\")"
  }
  MappedKind.INT -> "node.int(\"${p.name}\", ${defaultInt(p.defaultExpr)})"
  MappedKind.BOOL -> "node.bool(\"${p.name}\", ${defaultBool(p.defaultExpr)})"
  MappedKind.DOUBLE -> "node.dbl(\"${p.name}\", ${defaultDouble(p.defaultExpr)})"
  MappedKind.FLOAT -> "node.dbl(\"${p.name}\", ${defaultDouble(p.defaultExpr)}).toFloat()"
  MappedKind.INT_LIST -> "node.intList(\"${p.name}\")"
  MappedKind.FLOAT_LIST -> "node.floatList(\"${p.name}\")"
  MappedKind.DP -> "Dp(node.dbl(\"${p.name}\", ${defaultDouble(p.defaultExpr?.removePrefix("Dp(")?.removeSuffix(")"))}))"
  MappedKind.CONSTRAINT -> "constraintOf(node.int(\"${p.name}\", ${constraintDefault(p.defaultExpr)}))"
  MappedKind.CROSS_AXIS -> "crossAxisOf(node.int(\"${p.name}\", ${crossAxisDefault(p.defaultExpr)}))"
  MappedKind.MAIN_AXIS -> "mainAxisOf(node.int(\"${p.name}\", ${mainAxisDefault(p.defaultExpr)}))"
}

fun emitRenderNode(widgets: List<WidgetPlan.Include>): String = buildString {
  val sorted = widgets.sortedBy { it.name }
  appendLine("// GENERATED by :portal-schema-codegen — do not edit. Run ./gradlew :portal-schema-codegen:generatePortalCode")
  appendLine("package dev.keliver.portal.render")
  appendLine()
  appendLine("import androidx.compose.runtime.Composable")
  appendLine("import dev.keliver.portal.WidgetNode")
  appendLine("import dev.keliver.portal.bool")
  appendLine("import dev.keliver.portal.dbl")
  appendLine("import dev.keliver.portal.floatList")
  appendLine("import dev.keliver.portal.int")
  appendLine("import dev.keliver.portal.intList")
  appendLine("import dev.keliver.portal.str")
  if (sorted.any { w -> w.props.any { it.kind == MappedKind.DP } }) appendLine("import dev.keliver.ui.Dp")
  for (w in sorted) appendLine("import ${w.composePackage}.${w.name}")
  appendLine()
  appendLine("/** Interprets a portal WidgetNode tree as live keliver composables. */")
  appendLine("@Composable")
  appendLine("fun RenderNode(node: WidgetNode) {")
  appendLine("  when (node.type) {")
  for (w in sorted) {
    append("    \"${w.name}\" -> ${w.name}(")
    if (w.props.isNotEmpty()) {
      appendLine()
      for (p in w.props) appendLine("      ${p.name} = ${getterExpr(p)},")
      append("    )")
    } else {
      append(")")
    }
    if (w.hasChildren) append(" { node.children.forEach { RenderNode(it) } }")
    appendLine()
  }
  appendLine("    else -> StyledText(text = \"\\u26a0 unknown widget: \${node.type}\", colorArgb = -5238254)")
  appendLine("  }")
  appendLine("}")
}
