package dev.keliver.portal.codegen

// P3: the interpreter reads through the *B getters (portal-render), which
// resolve Bind values against PreviewBindings.mocks before falling back.
internal fun getterExpr(p: MappedProp): String = when (p.kind) {
  MappedKind.TEXT -> {
    val d = defaultString(p.defaultExpr).replace("\\", "\\\\").replace("\"", "\\\"")
    if (d.isEmpty()) "node.strB(\"${p.name}\")" else "node.strB(\"${p.name}\", \"$d\")"
  }
  MappedKind.INT -> "node.intB(\"${p.name}\", ${defaultInt(p.defaultExpr)})"
  MappedKind.BOOL -> "node.boolB(\"${p.name}\", ${defaultBool(p.defaultExpr)})"
  MappedKind.DOUBLE -> "node.dblB(\"${p.name}\", ${defaultDouble(p.defaultExpr)})"
  MappedKind.FLOAT -> "node.dblB(\"${p.name}\", ${defaultDouble(p.defaultExpr)}).toFloat()"
  MappedKind.INT_LIST -> "node.intList(\"${p.name}\")"
  MappedKind.FLOAT_LIST -> "node.floatList(\"${p.name}\")"
  MappedKind.DP -> "Dp(node.dblB(\"${p.name}\", ${defaultDouble(p.defaultExpr?.removePrefix("Dp(")?.removeSuffix(")"))}))"
  MappedKind.CONSTRAINT -> "constraintOf(node.intB(\"${p.name}\", ${constraintDefault(p.defaultExpr)}))"
  MappedKind.CROSS_AXIS -> "crossAxisOf(node.intB(\"${p.name}\", ${crossAxisDefault(p.defaultExpr)}))"
  MappedKind.MAIN_AXIS -> "mainAxisOf(node.intB(\"${p.name}\", ${mainAxisDefault(p.defaultExpr)}))"
  MappedKind.OVERFLOW -> "overflowOf(node.intB(\"${p.name}\", ${overflowDefault(p.defaultExpr)}))"
}

/** Lambda wiring for a nullable event prop holding an Action. */
internal fun eventExpr(e: EventPlan): String {
  val lambda = when (e.paramCount) {
    0 -> "{ PreviewBindings.fire(n) }"
    else -> "{ ${List(e.paramCount) { "_" }.joinToString(", ")} -> PreviewBindings.fire(n) }"
  }
  return "node.actionOf(\"${e.name}\")?.let { n -> $lambda }"
}

fun emitRenderNode(widgets: List<WidgetPlan.Include>, modifiers: List<ModPlan> = emptyList()): String = buildString {
  val sorted = widgets.sortedBy { it.name }
  val mods = modifiers.sortedBy { it.name }
  appendLine("// GENERATED by :portal-schema-codegen — do not edit. Run ./gradlew :portal-schema-codegen:generatePortalCode")
  appendLine("package dev.keliver.portal.render")
  appendLine()
  appendLine("import androidx.compose.runtime.Composable")
  if (mods.isNotEmpty()) appendLine("import dev.keliver.Modifier")
  appendLine("import dev.keliver.portal.WidgetNode")
  appendLine("import dev.keliver.portal.bool")
  appendLine("import dev.keliver.portal.floatList")
  appendLine("import dev.keliver.portal.intList")
  if (sorted.any { w -> w.props.any { it.kind == MappedKind.DP } }) appendLine("import dev.keliver.ui.Dp")
  for (w in sorted) appendLine("import ${w.composePackage}.${w.name}")
  for (m in mods) appendLine("import ${m.composePackage}.${m.extensionName}")
  appendLine()
  appendLine("/** Interprets a portal WidgetNode tree as live keliver composables. */")
  appendLine("@Composable")
  appendLine("fun RenderNode(node: WidgetNode) {")
  appendLine("  when (node.type) {")
  // M5/P2: Condition honors a boolean mock (default shown); Repeat renders
  // rowCount() mock rows with item binds resolved per row.
  appendLine("    \"Condition\" -> {")
  appendLine("      val field = (node.props[\"field\"] as? String) ?: \"\"")
  appendLine("      if (PreviewBindings.mocks[field]?.toBooleanStrictOrNull() != false) {")
  appendLine("        Column { node.children.forEach { RenderNode(it) } }")
  appendLine("      }")
  appendLine("    }")
  appendLine("    \"Repeat\" -> Column {")
  appendLine("      val itemVar = (node.props[\"item\"] as? String) ?: \"item\"")
  appendLine("      val itemsField = (node.props[\"items\"] as? String) ?: \"items\"")
  appendLine("      repeat(PreviewBindings.rowCount(itemsField)) { i ->")
  appendLine("        node.children.forEach { RenderNode(PreviewBindings.mockItemRow(it, itemVar, i)) }")
  appendLine("      }")
  appendLine("    }")
  for (w in sorted) {
    appendLine("    \"${w.name}\" -> ${w.name}(")
    if (mods.isNotEmpty()) appendLine("      modifier = nodeModifier(node),")
    for (p in w.props) appendLine("      ${p.name} = ${getterExpr(p)},")
    for (e in w.events) appendLine("      ${e.name} = ${eventExpr(e)},")
    append("    )")
    if (w.hasChildren) append(" { node.children.forEach { RenderNode(it) } }")
    appendLine()
  }
  appendLine("    else -> StyledText(text = \"\\u26a0 unknown widget: \${node.type}\", colorArgb = -5238254)")
  appendLine("  }")
  appendLine("}")
  if (mods.isNotEmpty()) {
    appendLine()
    appendLine("/** Builds the Modifier chain from a node's namespaced \"mod.*\" props. */")
    appendLine("private fun nodeModifier(node: WidgetNode): Modifier {")
    appendLine("  var m: Modifier = Modifier")
    for (mod in mods) {
      if (mod.props.isEmpty()) {
        appendLine("  if (node.bool(\"mod.${mod.name}\")) m = m.${mod.extensionName}()")
      } else {
        val presence = mod.props.joinToString(" || ") { "\"mod.${mod.name}.${it.name}\" in node.props" }
        val args = mod.props.joinToString(", ") { p -> getterExpr(p.copy(name = "mod.${mod.name}.${p.name}")) }
        appendLine("  if ($presence) m = m.${mod.extensionName}($args)")
      }
    }
    appendLine("  return m")
    appendLine("}")
  }
}
