[dev.konduit.treehouse.AppLifecycle]

functions = [
  # fun close(): kotlin.Unit
  "moYx+T3e",

  # fun sendFrame(kotlin.Long): kotlin.Unit
  "5nQA0rL/",

  # fun start(dev.konduit.treehouse.AppLifecycle.Host): kotlin.Unit
  "Xd61ecfL",

  # val guestProtocolVersion: dev.konduit.protocol.RedwoodVersion
  "0iFPbldz",
]

[dev.konduit.treehouse.AppLifecycle.Host]

functions = [
  # fun close(): kotlin.Unit
  "moYx+T3e",

  # fun handleUncaughtException(kotlin.Throwable): kotlin.Unit
  "Hls+uhG7",

  # fun onUnknownEvent(dev.konduit.protocol.WidgetTag, dev.konduit.protocol.EventTag): kotlin.Unit
  "jmKreoSS",

  # fun onUnknownEventNode(dev.konduit.protocol.Id, dev.konduit.protocol.EventTag): kotlin.Unit
  "fm35ryMh",

  # fun requestFrame(): kotlin.Unit
  "/TkBiP/u",

  # val hostProtocolVersion: dev.konduit.protocol.RedwoodVersion
  "4ifoT9Ua",
]

[dev.konduit.treehouse.AppService]

functions = [
  # fun close(): kotlin.Unit
  "moYx+T3e",

  # val appLifecycle: dev.konduit.treehouse.AppLifecycle
  "odhmO/d6",
]

[dev.konduit.treehouse.CancellableService]

functions = [
  # fun cancel(): kotlin.Unit
  "EhTc1FUm",

  # fun close(): kotlin.Unit
  "moYx+T3e",
]

[dev.konduit.treehouse.ChangesSinkService]

functions = [
  # fun close(): kotlin.Unit
  "moYx+T3e",

  # fun sendChanges(kotlin.collections.List): kotlin.Unit
  "W8qOuU0t",
]

[dev.konduit.treehouse.OnBackPressedCallbackService]

functions = [
  # fun close(): kotlin.Unit
  "moYx+T3e",

  # fun handleOnBackPressed(): kotlin.Unit
  "NjIN59uX",

  # val isEnabled: kotlinx.coroutines.flow.StateFlow<kotlin.Boolean>
  "TAJYS/cz",
]

[dev.konduit.treehouse.OnBackPressedDispatcherService]

functions = [
  # fun addCallback(dev.konduit.treehouse.OnBackPressedCallbackService): dev.konduit.treehouse.CancellableService
  "F7ShXQYg",

  # fun close(): kotlin.Unit
  "moYx+T3e",
]

[dev.konduit.treehouse.ZiplineTreehouseUi]

functions = [
  # fun close(): kotlin.Unit
  "moYx+T3e",

  # fun sendEvent(dev.konduit.protocol.Event): kotlin.Unit
  "NSFL6TSu",

  # fun snapshotState(): dev.konduit.treehouse.StateSnapshot
  "mPBGCHFl",

  # fun start(dev.konduit.treehouse.ZiplineTreehouseUi.Host): kotlin.Unit
  "h9yZr91W",
]

[dev.konduit.treehouse.ZiplineTreehouseUi.Host]

functions = [
  # fun addOnBackPressedCallback(dev.konduit.treehouse.OnBackPressedCallbackService): dev.konduit.treehouse.CancellableService
  "2nRsPBzK",

  # fun close(): kotlin.Unit
  "moYx+T3e",

  # fun sendChanges(kotlin.collections.List): kotlin.Unit
  "W8qOuU0t",

  # val stateSnapshot: dev.konduit.treehouse.StateSnapshot
  "hIDyr4lf",

  # val uiConfigurations: kotlinx.coroutines.flow.StateFlow<dev.konduit.ui.UiConfiguration>
  "iAkCX7gg",
]
