/*
 * spike/keliver-web portal — the local-first PORTAL SERVER (P2).
 * Evolved from the M2 tree relay: a JDK HttpServer (still no deps) that now
 * persists projects/screens/drafts as files under ~/.keliver-portal/ so a
 * browser refresh never loses work.
 *
 * Endpoints (all CORS-open; the browser editor drives them):
 *   GET  /projects                          -> ["default", ...]
 *   POST /projects            body=name     -> 204 (creates project + "main" screen)
 *   GET  /screens?project=P                 -> ["main", ...]
 *   POST /screens?project=P   body=name     -> 204
 *   GET  /draft?project=P&screen=S          -> stored tree JSON or {}
 *   PUT  /draft?project=P&screen=S body=json-> 204
 *   POST /active?project=P&screen=S         -> 204 (which screen the device mirrors)
 *   GET|POST /tree                          -> LEGACY, unchanged shape: the ACTIVE
 *                                              screen's draft. The device guest keeps
 *                                              polling GET /tree exactly as before.
 *
 * Store: ~/.keliver-portal/<project>/<screen>.json ; active screen in
 * ~/.keliver-portal/active (two lines: project, screen). default/main auto-created.
 * Binds 0.0.0.0 so the emulator reaches it at 10.0.2.2:8077.
 */
import com.sun.net.httpserver.HttpExchange
import com.sun.net.httpserver.HttpServer
import dev.keliver.portal.deserializeTree
import dev.keliver.portal.exportKotlin
import java.io.File
import java.net.InetSocketAddress
import java.net.URLDecoder
import java.security.KeyPairGenerator
import java.security.MessageDigest

private const val PORT = 8077

private val root = File(System.getProperty("user.home"), ".keliver-portal")
private val activeFile = File(root, "active")
private val keysDir = File(root, "keys")
private val bundlesDir = File(root, "bundles")

/** The konduit checkout the publish step compiles in. */
private val repoDir = File(System.getenv("PORTAL_REPO") ?: System.getProperty("user.dir"))

/** project/screen names are path segments — restrict to a safe charset. */
private fun safe(name: String): String = name.replace(Regex("[^A-Za-z0-9._-]"), "_").ifEmpty { "unnamed" }

private fun screenFile(project: String, screen: String) = File(File(root, safe(project)), "${safe(screen)}.json")

private fun activeScreen(): Pair<String, String> {
  val lines = runCatching { activeFile.readLines() }.getOrDefault(emptyList())
  return (lines.getOrNull(0) ?: "default") to (lines.getOrNull(1) ?: "main")
}

private fun setActive(project: String, screen: String) {
  activeFile.writeText("${safe(project)}\n${safe(screen)}\n")
}

private fun ensureDefaults() {
  root.mkdirs()
  val main = screenFile("default", "main")
  if (!main.exists()) { main.parentFile.mkdirs(); main.writeText("{}") }
  if (!activeFile.exists()) setActive("default", "main")
  ensureKeys()
  bundlesDir.mkdirs()
}

private fun hex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }

/**
 * P4: the project signing keypair. Zipline wants raw 32-byte Ed25519 keys as
 * hex; the JDK wraps them in PKCS#8/X.509 — the raw key is the last 32 bytes.
 */
private fun ensureKeys() {
  keysDir.mkdirs()
  val priv = File(keysDir, "ed25519.priv")
  val pub = File(keysDir, "ed25519.pub")
  if (priv.exists() && pub.exists()) return
  val kp = KeyPairGenerator.getInstance("Ed25519").generateKeyPair()
  fun raw32(encoded: ByteArray) = encoded.copyOfRange(encoded.size - 32, encoded.size)
  priv.writeText(hex(raw32(kp.private.encoded)))
  pub.writeText(hex(raw32(kp.public.encoded)))
  println("portal-server: generated Ed25519 signing keypair in $keysDir")
}

// ---------------------------------------------------------------------------
// P4 publish pipeline

private fun nextBundleVersion(): Int =
  (bundlesDir.listFiles { f -> f.isDirectory && f.name.startsWith("v") }
    ?.mapNotNull { it.name.removePrefix("v").toIntOrNull() }?.maxOrNull() ?: 0) + 1

/** tree json -> generated guest sources -> gradle compile+sign -> versioned store. Returns (ok, log). */
private fun publish(): Pair<Boolean, String> {
  val log = StringBuilder()
  val (p, s) = activeScreen()
  val draft = screenFile(p, s)
  if (!draft.exists() || draft.readText().trim() == "{}") return false to "nothing to publish: $p/$s is empty"
  val tree = deserializeTree(draft.readText())
  val contract = dev.keliver.portal.collectContract(tree)

  val genDir = File(repoDir, "portal-published-guest/src/jsMain/kotlin/generated")
  genDir.mkdirs()
  val screenSrc = "package dev.keliver.portalpublished\n\n" + exportKotlin(tree, functionName = "PublishedScreen")
  File(genDir, "PublishedScreen.kt").writeText(screenSrc)
  val entry = buildString {
    appendLine("package dev.keliver.portalpublished")
    appendLine()
    appendLine("import androidx.compose.runtime.Composable")
    appendLine()
    appendLine("// GENERATED by the portal publish step — do not edit.")
    appendLine("@Composable")
    if (contract.isEmpty) {
      appendLine("fun PublishedEntry() { PublishedScreen() }")
    } else {
      appendLine("// This screen has a contract: engineers must provide `PublishedBindings`")
      appendLine("// (an object implementing PublishedScreenBindings) under src/jsMain/kotlin/impl/.")
      appendLine("fun PublishedEntry() { PublishedScreen(PublishedBindings) }")
    }
  }
  File(genDir, "PublishedEntry.kt").writeText(entry)
  log.appendLine("publish: exported $p/$s (contract fields=${contract.fields.keys} actions=${contract.actions})")

  val gradlew = File(repoDir, "gradlew").absolutePath
  val proc = ProcessBuilder(gradlew, ":portal-published-guest:compileDevelopmentZipline", "--console=plain")
    .directory(repoDir)
    .redirectErrorStream(true)
    .start()
  val out = proc.inputStream.bufferedReader().readText()
  val code = proc.waitFor()
  log.appendLine(out.lines().filter { it.isNotBlank() }.takeLast(30).joinToString("\n"))
  if (code != 0) return false to log.appendLine("publish FAILED (gradle exit $code)").toString()

  val ziplineOut = File(repoDir, "portal-published-guest/build/zipline/Development")
  if (!ziplineOut.exists()) return false to log.appendLine("publish FAILED: no zipline output at $ziplineOut").toString()
  val version = nextBundleVersion()
  val dest = File(bundlesDir, "v$version")
  ziplineOut.copyRecursively(dest, overwrite = true)
  val treeHash = hex(MessageDigest.getInstance("SHA-256").digest(draft.readBytes())).take(16)
  File(dest, "meta.json").writeText(
    "{\"version\":$version,\"widgetVersion\":1,\"project\":\"$p\",\"screen\":\"$s\",\"treeHash\":\"$treeHash\",\"createdAt\":${System.currentTimeMillis()}}",
  )
  log.appendLine("publish OK: bundle v$version (widgetVersion=1, treeHash=$treeHash) -> $dest")
  return true to log.toString()
}

private fun cors(ex: HttpExchange) {
  ex.responseHeaders.add("Access-Control-Allow-Origin", "*")
  ex.responseHeaders.add("Access-Control-Allow-Methods", "GET, POST, PUT, OPTIONS")
  ex.responseHeaders.add("Access-Control-Allow-Headers", "*")
}

private fun query(ex: HttpExchange): Map<String, String> =
  (ex.requestURI.rawQuery ?: "").split('&').filter { '=' in it }.associate {
    val (k, v) = it.split('=', limit = 2)
    k to URLDecoder.decode(v, "UTF-8")
  }

private fun respond(ex: HttpExchange, code: Int, body: String? = null, contentType: String = "application/json") {
  if (body == null) { ex.sendResponseHeaders(code, -1); ex.close(); return }
  val bytes = body.encodeToByteArray()
  ex.responseHeaders.add("Content-Type", contentType)
  ex.sendResponseHeaders(code, bytes.size.toLong())
  ex.responseBody.use { it.write(bytes) }
}

private fun jsonList(items: List<String>): String =
  items.joinToString(",", "[", "]") { "\"${it.replace("\"", "\\\"")}\"" }

private fun handle(ex: HttpExchange, block: () -> Unit) {
  cors(ex)
  if (ex.requestMethod == "OPTIONS") { respond(ex, 204); return }
  runCatching(block).onFailure {
    println("portal-server: ${ex.requestURI} failed: $it")
    runCatching { respond(ex, 500, "{\"error\":\"${it.message}\"}") }
  }
}

fun main() {
  ensureDefaults()
  val server = HttpServer.create(InetSocketAddress(PORT), 0)

  server.createContext("/projects") { ex ->
    handle(ex) {
      when (ex.requestMethod) {
        "GET" -> respond(ex, 200, jsonList(root.listFiles { f -> f.isDirectory }?.map { it.name }?.sorted() ?: emptyList()))
        "POST" -> {
          val name = safe(ex.requestBody.readBytes().decodeToString().trim())
          val main = screenFile(name, "main")
          main.parentFile.mkdirs()
          if (!main.exists()) main.writeText("{}")
          respond(ex, 204)
        }
        else -> respond(ex, 405)
      }
    }
  }

  server.createContext("/screens") { ex ->
    handle(ex) {
      val project = safe(query(ex)["project"] ?: "default")
      when (ex.requestMethod) {
        "GET" -> respond(
          ex, 200,
          jsonList(
            File(root, project).listFiles { f -> f.name.endsWith(".json") }
              ?.map { it.name.removeSuffix(".json") }?.sorted() ?: emptyList(),
          ),
        )
        "POST" -> {
          val name = safe(ex.requestBody.readBytes().decodeToString().trim())
          val f = screenFile(project, name)
          f.parentFile.mkdirs()
          if (!f.exists()) f.writeText("{}")
          respond(ex, 204)
        }
        else -> respond(ex, 405)
      }
    }
  }

  server.createContext("/draft") { ex ->
    handle(ex) {
      val q = query(ex)
      val project = q["project"] ?: "default"
      val screen = q["screen"] ?: "main"
      val f = screenFile(project, screen)
      when (ex.requestMethod) {
        "GET" -> respond(ex, 200, if (f.exists()) f.readText() else "{}")
        "PUT" -> {
          f.parentFile.mkdirs()
          f.writeText(ex.requestBody.readBytes().decodeToString())
          respond(ex, 204)
        }
        else -> respond(ex, 405)
      }
    }
  }

  server.createContext("/active") { ex ->
    handle(ex) {
      when (ex.requestMethod) {
        "GET" -> {
          val (p, s) = activeScreen()
          respond(ex, 200, "{\"project\":\"$p\",\"screen\":\"$s\"}")
        }
        "POST" -> {
          val q = query(ex)
          setActive(q["project"] ?: "default", q["screen"] ?: "main")
          respond(ex, 204)
        }
        else -> respond(ex, 405)
      }
    }
  }

  // LEGACY device endpoint — unchanged wire shape. Mirrors the ACTIVE screen's draft.
  server.createContext("/tree") { ex ->
    handle(ex) {
      val (p, s) = activeScreen()
      val f = screenFile(p, s)
      when (ex.requestMethod) {
        "GET" -> respond(ex, 200, if (f.exists()) f.readText() else "{}")
        "POST" -> {
          f.parentFile.mkdirs()
          f.writeText(ex.requestBody.readBytes().decodeToString())
          respond(ex, 204)
        }
        else -> respond(ex, 405)
      }
    }
  }

  server.createContext("/publickey") { ex ->
    handle(ex) { respond(ex, 200, File(keysDir, "ed25519.pub").readText().trim(), contentType = "text/plain") }
  }

  server.createContext("/publish") { ex ->
    handle(ex) {
      when (ex.requestMethod) {
        "POST" -> {
          val (ok, logText) = publish()
          respond(ex, if (ok) 200 else 422, logText, contentType = "text/plain")
        }
        else -> respond(ex, 405)
      }
    }
  }

  // /bundles/latest?widgetVersion=W -> newest compatible bundle; /bundles/vN/<file> -> static.
  server.createContext("/bundles") { ex ->
    handle(ex) {
      val path = ex.requestURI.path.removePrefix("/bundles").trimStart('/')
      when {
        path == "latest" -> {
          val want = query(ex)["widgetVersion"]?.toIntOrNull() ?: Int.MAX_VALUE
          val best = bundlesDir.listFiles { f -> f.isDirectory && f.name.startsWith("v") }
            ?.filter { dir ->
              val meta = File(dir, "meta.json")
              val recorded = Regex("\"widgetVersion\":(\\d+)").find(meta.takeIf { it.exists() }?.readText() ?: "")
                ?.groupValues?.get(1)?.toIntOrNull() ?: Int.MAX_VALUE
              recorded <= want
            }
            ?.maxByOrNull { it.name.removePrefix("v").toIntOrNull() ?: 0 }
          if (best == null) {
            respond(ex, 404, "{\"error\":\"no compatible bundle\"}")
          } else {
            respond(ex, 200, "{\"version\":${best.name.removePrefix("v")},\"manifestUrl\":\"/bundles/${best.name}/manifest.zipline.json\"}")
          }
        }
        else -> {
          val f = File(bundlesDir, path)
          // stay inside the store; serve bundle files raw
          if (!f.canonicalPath.startsWith(bundlesDir.canonicalPath) || !f.isFile) {
            respond(ex, 404)
          } else {
            val bytes = f.readBytes()
            ex.responseHeaders.add("Content-Type", if (f.name.endsWith(".json")) "application/json" else "application/octet-stream")
            ex.sendResponseHeaders(200, bytes.size.toLong())
            ex.responseBody.use { it.write(bytes) }
          }
        }
      }
    }
  }

  server.executor = null
  server.start()
  println("portal-server: :$PORT — store=$root repo=$repoDir  active=${activeScreen()}")
  println("portal-server: endpoints /projects /screens /draft /active /tree /publickey /publish /bundles")
}
